// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: common/v1/media_service.proto

package commonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaService_MerchantUploadSingleMedia_FullMethodName = "/common.v1.MediaService/MerchantUploadSingleMedia"
	MediaService_MerchantUploadBatchMedia_FullMethodName  = "/common.v1.MediaService/MerchantUploadBatchMedia"
	MediaService_AdminUploadSingleMedia_FullMethodName    = "/common.v1.MediaService/AdminUploadSingleMedia"
	MediaService_AdminUploadBatchMedia_FullMethodName     = "/common.v1.MediaService/AdminUploadBatchMedia"
	MediaService_UserUploadSingleMedia_FullMethodName     = "/common.v1.MediaService/UserUploadSingleMedia"
	MediaService_UserUploadBatchMedia_FullMethodName      = "/common.v1.MediaService/UserUploadBatchMedia"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	MerchantUploadSingleMedia(ctx context.Context, in *UploadSingleMediaRequest, opts ...grpc.CallOption) (*UploadSingleMediaResponse, error)
	MerchantUploadBatchMedia(ctx context.Context, in *UploadBatchMediaRequest, opts ...grpc.CallOption) (*UploadBatchMediaResponse, error)
	AdminUploadSingleMedia(ctx context.Context, in *UploadSingleMediaRequest, opts ...grpc.CallOption) (*UploadSingleMediaResponse, error)
	AdminUploadBatchMedia(ctx context.Context, in *UploadBatchMediaRequest, opts ...grpc.CallOption) (*UploadBatchMediaResponse, error)
	UserUploadSingleMedia(ctx context.Context, in *UploadSingleMediaRequest, opts ...grpc.CallOption) (*UploadSingleMediaResponse, error)
	UserUploadBatchMedia(ctx context.Context, in *UploadBatchMediaRequest, opts ...grpc.CallOption) (*UploadBatchMediaResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) MerchantUploadSingleMedia(ctx context.Context, in *UploadSingleMediaRequest, opts ...grpc.CallOption) (*UploadSingleMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSingleMediaResponse)
	err := c.cc.Invoke(ctx, MediaService_MerchantUploadSingleMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) MerchantUploadBatchMedia(ctx context.Context, in *UploadBatchMediaRequest, opts ...grpc.CallOption) (*UploadBatchMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadBatchMediaResponse)
	err := c.cc.Invoke(ctx, MediaService_MerchantUploadBatchMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) AdminUploadSingleMedia(ctx context.Context, in *UploadSingleMediaRequest, opts ...grpc.CallOption) (*UploadSingleMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSingleMediaResponse)
	err := c.cc.Invoke(ctx, MediaService_AdminUploadSingleMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) AdminUploadBatchMedia(ctx context.Context, in *UploadBatchMediaRequest, opts ...grpc.CallOption) (*UploadBatchMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadBatchMediaResponse)
	err := c.cc.Invoke(ctx, MediaService_AdminUploadBatchMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UserUploadSingleMedia(ctx context.Context, in *UploadSingleMediaRequest, opts ...grpc.CallOption) (*UploadSingleMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSingleMediaResponse)
	err := c.cc.Invoke(ctx, MediaService_UserUploadSingleMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UserUploadBatchMedia(ctx context.Context, in *UploadBatchMediaRequest, opts ...grpc.CallOption) (*UploadBatchMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadBatchMediaResponse)
	err := c.cc.Invoke(ctx, MediaService_UserUploadBatchMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations should embed UnimplementedMediaServiceServer
// for forward compatibility.
type MediaServiceServer interface {
	MerchantUploadSingleMedia(context.Context, *UploadSingleMediaRequest) (*UploadSingleMediaResponse, error)
	MerchantUploadBatchMedia(context.Context, *UploadBatchMediaRequest) (*UploadBatchMediaResponse, error)
	AdminUploadSingleMedia(context.Context, *UploadSingleMediaRequest) (*UploadSingleMediaResponse, error)
	AdminUploadBatchMedia(context.Context, *UploadBatchMediaRequest) (*UploadBatchMediaResponse, error)
	UserUploadSingleMedia(context.Context, *UploadSingleMediaRequest) (*UploadSingleMediaResponse, error)
	UserUploadBatchMedia(context.Context, *UploadBatchMediaRequest) (*UploadBatchMediaResponse, error)
}

// UnimplementedMediaServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaServiceServer struct{}

func (UnimplementedMediaServiceServer) MerchantUploadSingleMedia(context.Context, *UploadSingleMediaRequest) (*UploadSingleMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MerchantUploadSingleMedia not implemented")
}
func (UnimplementedMediaServiceServer) MerchantUploadBatchMedia(context.Context, *UploadBatchMediaRequest) (*UploadBatchMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MerchantUploadBatchMedia not implemented")
}
func (UnimplementedMediaServiceServer) AdminUploadSingleMedia(context.Context, *UploadSingleMediaRequest) (*UploadSingleMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUploadSingleMedia not implemented")
}
func (UnimplementedMediaServiceServer) AdminUploadBatchMedia(context.Context, *UploadBatchMediaRequest) (*UploadBatchMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUploadBatchMedia not implemented")
}
func (UnimplementedMediaServiceServer) UserUploadSingleMedia(context.Context, *UploadSingleMediaRequest) (*UploadSingleMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserUploadSingleMedia not implemented")
}
func (UnimplementedMediaServiceServer) UserUploadBatchMedia(context.Context, *UploadBatchMediaRequest) (*UploadBatchMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserUploadBatchMedia not implemented")
}
func (UnimplementedMediaServiceServer) testEmbeddedByValue() {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_MerchantUploadSingleMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSingleMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).MerchantUploadSingleMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_MerchantUploadSingleMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).MerchantUploadSingleMedia(ctx, req.(*UploadSingleMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_MerchantUploadBatchMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBatchMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).MerchantUploadBatchMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_MerchantUploadBatchMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).MerchantUploadBatchMedia(ctx, req.(*UploadBatchMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_AdminUploadSingleMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSingleMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).AdminUploadSingleMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_AdminUploadSingleMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).AdminUploadSingleMedia(ctx, req.(*UploadSingleMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_AdminUploadBatchMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBatchMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).AdminUploadBatchMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_AdminUploadBatchMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).AdminUploadBatchMedia(ctx, req.(*UploadBatchMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UserUploadSingleMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSingleMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).UserUploadSingleMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_UserUploadSingleMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).UserUploadSingleMedia(ctx, req.(*UploadSingleMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UserUploadBatchMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBatchMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).UserUploadBatchMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_UserUploadBatchMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).UserUploadBatchMedia(ctx, req.(*UploadBatchMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.v1.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MerchantUploadSingleMedia",
			Handler:    _MediaService_MerchantUploadSingleMedia_Handler,
		},
		{
			MethodName: "MerchantUploadBatchMedia",
			Handler:    _MediaService_MerchantUploadBatchMedia_Handler,
		},
		{
			MethodName: "AdminUploadSingleMedia",
			Handler:    _MediaService_AdminUploadSingleMedia_Handler,
		},
		{
			MethodName: "AdminUploadBatchMedia",
			Handler:    _MediaService_AdminUploadBatchMedia_Handler,
		},
		{
			MethodName: "UserUploadSingleMedia",
			Handler:    _MediaService_UserUploadSingleMedia_Handler,
		},
		{
			MethodName: "UserUploadBatchMedia",
			Handler:    _MediaService_UserUploadBatchMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/v1/media_service.proto",
}
