// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/media_service.proto

package commonv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_common_v1_media_service_proto protoreflect.FileDescriptor

const file_common_v1_media_service_proto_rawDesc = "" +
	"\n" +
	"\x1dcommon/v1/media_service.proto\x12\tcommon.v1\x1a\x1ecommon/v1/media_messages.proto\x1a\x1cgoogle/api/annotations.proto2\x86\a\n" +
	"\fMediaService\x12\x98\x01\n" +
	"\x19MerchantUploadSingleMedia\x12#.common.v1.UploadSingleMediaRequest\x1a$.common.v1.UploadSingleMediaResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/merchants/media/upload/single\x12\x94\x01\n" +
	"\x18MerchantUploadBatchMedia\x12\".common.v1.UploadBatchMediaRequest\x1a#.common.v1.UploadBatchMediaResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/merchants/media/upload/batch\x12\x91\x01\n" +
	"\x16AdminUploadSingleMedia\x12#.common.v1.UploadSingleMediaRequest\x1a$.common.v1.UploadSingleMediaResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/admin/media/upload/single\x12\x8d\x01\n" +
	"\x15AdminUploadBatchMedia\x12\".common.v1.UploadBatchMediaRequest\x1a#.common.v1.UploadBatchMediaResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/admin/media/upload/batch\x12\x90\x01\n" +
	"\x15UserUploadSingleMedia\x12#.common.v1.UploadSingleMediaRequest\x1a$.common.v1.UploadSingleMediaResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/users/media/upload/single\x12\x8c\x01\n" +
	"\x14UserUploadBatchMedia\x12\".common.v1.UploadBatchMediaRequest\x1a#.common.v1.UploadBatchMediaResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/users/media/upload/batchBCZAgithub.com/khoitran2003/sportinas-be-proto-gen/common/v1;commonv1b\x06proto3"

var file_common_v1_media_service_proto_goTypes = []any{
	(*UploadSingleMediaRequest)(nil),  // 0: common.v1.UploadSingleMediaRequest
	(*UploadBatchMediaRequest)(nil),   // 1: common.v1.UploadBatchMediaRequest
	(*UploadSingleMediaResponse)(nil), // 2: common.v1.UploadSingleMediaResponse
	(*UploadBatchMediaResponse)(nil),  // 3: common.v1.UploadBatchMediaResponse
}
var file_common_v1_media_service_proto_depIdxs = []int32{
	0, // 0: common.v1.MediaService.MerchantUploadSingleMedia:input_type -> common.v1.UploadSingleMediaRequest
	1, // 1: common.v1.MediaService.MerchantUploadBatchMedia:input_type -> common.v1.UploadBatchMediaRequest
	0, // 2: common.v1.MediaService.AdminUploadSingleMedia:input_type -> common.v1.UploadSingleMediaRequest
	1, // 3: common.v1.MediaService.AdminUploadBatchMedia:input_type -> common.v1.UploadBatchMediaRequest
	0, // 4: common.v1.MediaService.UserUploadSingleMedia:input_type -> common.v1.UploadSingleMediaRequest
	1, // 5: common.v1.MediaService.UserUploadBatchMedia:input_type -> common.v1.UploadBatchMediaRequest
	2, // 6: common.v1.MediaService.MerchantUploadSingleMedia:output_type -> common.v1.UploadSingleMediaResponse
	3, // 7: common.v1.MediaService.MerchantUploadBatchMedia:output_type -> common.v1.UploadBatchMediaResponse
	2, // 8: common.v1.MediaService.AdminUploadSingleMedia:output_type -> common.v1.UploadSingleMediaResponse
	3, // 9: common.v1.MediaService.AdminUploadBatchMedia:output_type -> common.v1.UploadBatchMediaResponse
	2, // 10: common.v1.MediaService.UserUploadSingleMedia:output_type -> common.v1.UploadSingleMediaResponse
	3, // 11: common.v1.MediaService.UserUploadBatchMedia:output_type -> common.v1.UploadBatchMediaResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_media_service_proto_init() }
func file_common_v1_media_service_proto_init() {
	if File_common_v1_media_service_proto != nil {
		return
	}
	file_common_v1_media_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_media_service_proto_rawDesc), len(file_common_v1_media_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_v1_media_service_proto_goTypes,
		DependencyIndexes: file_common_v1_media_service_proto_depIdxs,
	}.Build()
	File_common_v1_media_service_proto = out.File
	file_common_v1_media_service_proto_goTypes = nil
	file_common_v1_media_service_proto_depIdxs = nil
}
