// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/media_messages.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadSingleMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalName  string                 `protobuf:"bytes,1,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSingleMediaRequest) Reset() {
	*x = UploadSingleMediaRequest{}
	mi := &file_common_v1_media_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSingleMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSingleMediaRequest) ProtoMessage() {}

func (x *UploadSingleMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_media_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSingleMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadSingleMediaRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_media_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UploadSingleMediaRequest) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *UploadSingleMediaRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadSingleMediaRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type UploadSingleMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSingleMediaResponse) Reset() {
	*x = UploadSingleMediaResponse{}
	mi := &file_common_v1_media_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSingleMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSingleMediaResponse) ProtoMessage() {}

func (x *UploadSingleMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_media_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSingleMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadSingleMediaResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_media_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UploadSingleMediaResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadSingleMediaResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type UploadBatchMediaRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Requests      []*UploadSingleMediaRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBatchMediaRequest) Reset() {
	*x = UploadBatchMediaRequest{}
	mi := &file_common_v1_media_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBatchMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBatchMediaRequest) ProtoMessage() {}

func (x *UploadBatchMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_media_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBatchMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadBatchMediaRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_media_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UploadBatchMediaRequest) GetRequests() []*UploadSingleMediaRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type UploadBatchMediaResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Responses     []*UploadSingleMediaResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBatchMediaResponse) Reset() {
	*x = UploadBatchMediaResponse{}
	mi := &file_common_v1_media_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBatchMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBatchMediaResponse) ProtoMessage() {}

func (x *UploadBatchMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_media_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBatchMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadBatchMediaResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_media_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UploadBatchMediaResponse) GetResponses() []*UploadSingleMediaResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_common_v1_media_messages_proto protoreflect.FileDescriptor

const file_common_v1_media_messages_proto_rawDesc = "" +
	"\n" +
	"\x1ecommon/v1/media_messages.proto\x12\tcommon.v1\"\x7f\n" +
	"\x18UploadSingleMediaRequest\x12#\n" +
	"\roriginal_name\x18\x01 \x01(\tR\foriginalName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\"J\n" +
	"\x19UploadSingleMediaResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"Z\n" +
	"\x17UploadBatchMediaRequest\x12?\n" +
	"\brequests\x18\x01 \x03(\v2#.common.v1.UploadSingleMediaRequestR\brequests\"^\n" +
	"\x18UploadBatchMediaResponse\x12B\n" +
	"\tresponses\x18\x01 \x03(\v2$.common.v1.UploadSingleMediaResponseR\tresponsesB6Z4github.com/Sportinas/be-proto-gen/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_media_messages_proto_rawDescOnce sync.Once
	file_common_v1_media_messages_proto_rawDescData []byte
)

func file_common_v1_media_messages_proto_rawDescGZIP() []byte {
	file_common_v1_media_messages_proto_rawDescOnce.Do(func() {
		file_common_v1_media_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_media_messages_proto_rawDesc), len(file_common_v1_media_messages_proto_rawDesc)))
	})
	return file_common_v1_media_messages_proto_rawDescData
}

var file_common_v1_media_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_v1_media_messages_proto_goTypes = []any{
	(*UploadSingleMediaRequest)(nil),  // 0: common.v1.UploadSingleMediaRequest
	(*UploadSingleMediaResponse)(nil), // 1: common.v1.UploadSingleMediaResponse
	(*UploadBatchMediaRequest)(nil),   // 2: common.v1.UploadBatchMediaRequest
	(*UploadBatchMediaResponse)(nil),  // 3: common.v1.UploadBatchMediaResponse
}
var file_common_v1_media_messages_proto_depIdxs = []int32{
	0, // 0: common.v1.UploadBatchMediaRequest.requests:type_name -> common.v1.UploadSingleMediaRequest
	1, // 1: common.v1.UploadBatchMediaResponse.responses:type_name -> common.v1.UploadSingleMediaResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_v1_media_messages_proto_init() }
func file_common_v1_media_messages_proto_init() {
	if File_common_v1_media_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_media_messages_proto_rawDesc), len(file_common_v1_media_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_media_messages_proto_goTypes,
		DependencyIndexes: file_common_v1_media_messages_proto_depIdxs,
		MessageInfos:      file_common_v1_media_messages_proto_msgTypes,
	}.Build()
	File_common_v1_media_messages_proto = out.File
	file_common_v1_media_messages_proto_goTypes = nil
	file_common_v1_media_messages_proto_depIdxs = nil
}
