// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/v1/catalog_messages.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SportCategory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NameVi         string                 `protobuf:"bytes,6,opt,name=name_vi,json=nameVi,proto3" json:"name_vi,omitempty"`
	NameEn         string                 `protobuf:"bytes,7,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Visible        bool                   `protobuf:"varint,9,opt,name=visible,proto3" json:"visible,omitempty"`
	GoogleIconData string                 `protobuf:"bytes,3,opt,name=google_icon_data,json=googleIconData,proto3" json:"google_icon_data,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SportCategory) Reset() {
	*x = SportCategory{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportCategory) ProtoMessage() {}

func (x *SportCategory) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SportCategory.ProtoReflect.Descriptor instead.
func (*SportCategory) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SportCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SportCategory) GetNameVi() string {
	if x != nil {
		return x.NameVi
	}
	return ""
}

func (x *SportCategory) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *SportCategory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SportCategory) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *SportCategory) GetGoogleIconData() string {
	if x != nil {
		return x.GoogleIconData
	}
	return ""
}

func (x *SportCategory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SportCategory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Sport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NameVi         string                 `protobuf:"bytes,8,opt,name=name_vi,json=nameVi,proto3" json:"name_vi,omitempty"`
	NameEn         string                 `protobuf:"bytes,9,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Visible        bool                   `protobuf:"varint,11,opt,name=visible,proto3" json:"visible,omitempty"`
	SportCode      string                 `protobuf:"bytes,12,opt,name=sport_code,json=sportCode,proto3" json:"sport_code,omitempty"`
	CategoryId     string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	GoogleIconData string                 `protobuf:"bytes,4,opt,name=google_icon_data,json=googleIconData,proto3" json:"google_icon_data,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Sport) Reset() {
	*x = Sport{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sport) ProtoMessage() {}

func (x *Sport) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sport.ProtoReflect.Descriptor instead.
func (*Sport) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Sport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sport) GetNameVi() string {
	if x != nil {
		return x.NameVi
	}
	return ""
}

func (x *Sport) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *Sport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Sport) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Sport) GetSportCode() string {
	if x != nil {
		return x.SportCode
	}
	return ""
}

func (x *Sport) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Sport) GetGoogleIconData() string {
	if x != nil {
		return x.GoogleIconData
	}
	return ""
}

func (x *Sport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Sport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListSportCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSportCategoriesRequest) Reset() {
	*x = ListSportCategoriesRequest{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSportCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSportCategoriesRequest) ProtoMessage() {}

func (x *ListSportCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSportCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListSportCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{2}
}

type ListSportCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*SportCategory       `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSportCategoriesResponse) Reset() {
	*x = ListSportCategoriesResponse{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSportCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSportCategoriesResponse) ProtoMessage() {}

func (x *ListSportCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSportCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListSportCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ListSportCategoriesResponse) GetCategories() []*SportCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetSportCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSportCategoryRequest) Reset() {
	*x = GetSportCategoryRequest{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSportCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSportCategoryRequest) ProtoMessage() {}

func (x *GetSportCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSportCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetSportCategoryRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetSportCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSportsRequest) Reset() {
	*x = ListSportsRequest{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSportsRequest) ProtoMessage() {}

func (x *ListSportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSportsRequest.ProtoReflect.Descriptor instead.
func (*ListSportsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ListSportsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type ListSportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sports        []*Sport               `protobuf:"bytes,1,rep,name=sports,proto3" json:"sports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSportsResponse) Reset() {
	*x = ListSportsResponse{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSportsResponse) ProtoMessage() {}

func (x *ListSportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSportsResponse.ProtoReflect.Descriptor instead.
func (*ListSportsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ListSportsResponse) GetSports() []*Sport {
	if x != nil {
		return x.Sports
	}
	return nil
}

type SportAttributeOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SportAttributeOption) Reset() {
	*x = SportAttributeOption{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportAttributeOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportAttributeOption) ProtoMessage() {}

func (x *SportAttributeOption) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SportAttributeOption.ProtoReflect.Descriptor instead.
func (*SportAttributeOption) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SportAttributeOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SportAttributeOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type SportAttributeField struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                    `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Options       []*SportAttributeOption `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	DefaultValue  string                  `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	DisplayOrder  int32                   `protobuf:"varint,7,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	IsActive      bool                    `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SportAttributeField) Reset() {
	*x = SportAttributeField{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportAttributeField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportAttributeField) ProtoMessage() {}

func (x *SportAttributeField) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SportAttributeField.ProtoReflect.Descriptor instead.
func (*SportAttributeField) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SportAttributeField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SportAttributeField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SportAttributeField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SportAttributeField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *SportAttributeField) GetOptions() []*SportAttributeOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SportAttributeField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *SportAttributeField) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *SportAttributeField) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetSportSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SportCode     string                 `protobuf:"bytes,1,opt,name=sport_code,json=sportCode,proto3" json:"sport_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSportSchemaRequest) Reset() {
	*x = GetSportSchemaRequest{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSportSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSportSchemaRequest) ProtoMessage() {}

func (x *GetSportSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSportSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSportSchemaRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GetSportSchemaRequest) GetSportCode() string {
	if x != nil {
		return x.SportCode
	}
	return ""
}

type GetSportSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SportCode     string                 `protobuf:"bytes,1,opt,name=sport_code,json=sportCode,proto3" json:"sport_code,omitempty"`
	Fields        []*SportAttributeField `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSportSchemaResponse) Reset() {
	*x = GetSportSchemaResponse{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSportSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSportSchemaResponse) ProtoMessage() {}

func (x *GetSportSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSportSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSportSchemaResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{10}
}

func (x *GetSportSchemaResponse) GetSportCode() string {
	if x != nil {
		return x.SportCode
	}
	return ""
}

func (x *GetSportSchemaResponse) GetFields() []*SportAttributeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Province struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Province) Reset() {
	*x = Province{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Province) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Province) ProtoMessage() {}

func (x *Province) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Province.ProtoReflect.Descriptor instead.
func (*Province) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Province) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Province) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type District struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ProvinceCode  string                 `protobuf:"bytes,2,opt,name=province_code,json=provinceCode,proto3" json:"province_code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *District) Reset() {
	*x = District{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *District) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*District) ProtoMessage() {}

func (x *District) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use District.ProtoReflect.Descriptor instead.
func (*District) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{12}
}

func (x *District) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *District) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

func (x *District) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Ward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	DistrictCode  string                 `protobuf:"bytes,2,opt,name=district_code,json=districtCode,proto3" json:"district_code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ward) Reset() {
	*x = Ward{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ward) ProtoMessage() {}

func (x *Ward) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ward.ProtoReflect.Descriptor instead.
func (*Ward) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Ward) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Ward) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

func (x *Ward) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProvincesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvincesRequest) Reset() {
	*x = ListProvincesRequest{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvincesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvincesRequest) ProtoMessage() {}

func (x *ListProvincesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvincesRequest.ProtoReflect.Descriptor instead.
func (*ListProvincesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ListProvincesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProvincesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provinces     []*Province            `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvincesResponse) Reset() {
	*x = ListProvincesResponse{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvincesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvincesResponse) ProtoMessage() {}

func (x *ListProvincesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvincesResponse.ProtoReflect.Descriptor instead.
func (*ListProvincesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ListProvincesResponse) GetProvinces() []*Province {
	if x != nil {
		return x.Provinces
	}
	return nil
}

type ListDistrictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProvinceCode  string                 `protobuf:"bytes,2,opt,name=province_code,json=provinceCode,proto3" json:"province_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDistrictsRequest) Reset() {
	*x = ListDistrictsRequest{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDistrictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDistrictsRequest) ProtoMessage() {}

func (x *ListDistrictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDistrictsRequest.ProtoReflect.Descriptor instead.
func (*ListDistrictsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{16}
}

func (x *ListDistrictsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListDistrictsRequest) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

type ListDistrictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Districts     []*District            `protobuf:"bytes,1,rep,name=districts,proto3" json:"districts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDistrictsResponse) Reset() {
	*x = ListDistrictsResponse{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDistrictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDistrictsResponse) ProtoMessage() {}

func (x *ListDistrictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDistrictsResponse.ProtoReflect.Descriptor instead.
func (*ListDistrictsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{17}
}

func (x *ListDistrictsResponse) GetDistricts() []*District {
	if x != nil {
		return x.Districts
	}
	return nil
}

type ListWardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DistrictCode  string                 `protobuf:"bytes,2,opt,name=district_code,json=districtCode,proto3" json:"district_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWardsRequest) Reset() {
	*x = ListWardsRequest{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardsRequest) ProtoMessage() {}

func (x *ListWardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardsRequest.ProtoReflect.Descriptor instead.
func (*ListWardsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ListWardsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListWardsRequest) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

type ListWardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wards         []*Ward                `protobuf:"bytes,1,rep,name=wards,proto3" json:"wards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWardsResponse) Reset() {
	*x = ListWardsResponse{}
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWardsResponse) ProtoMessage() {}

func (x *ListWardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWardsResponse.ProtoReflect.Descriptor instead.
func (*ListWardsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ListWardsResponse) GetWards() []*Ward {
	if x != nil {
		return x.Wards
	}
	return nil
}

var File_catalog_v1_catalog_messages_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_messages_proto_rawDesc = "" +
	"\n" +
	"!catalog/v1/catalog_messages.proto\x12\n" +
	"catalog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x02\n" +
	"\rSportCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aname_vi\x18\x06 \x01(\tR\x06nameVi\x12\x17\n" +
	"\aname_en\x18\a \x01(\tR\x06nameEn\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\avisible\x18\t \x01(\bR\avisible\x12(\n" +
	"\x10google_icon_data\x18\x03 \x01(\tR\x0egoogleIconData\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtJ\x04\b\x02\x10\x03\"\xe1\x02\n" +
	"\x05Sport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aname_vi\x18\b \x01(\tR\x06nameVi\x12\x17\n" +
	"\aname_en\x18\t \x01(\tR\x06nameEn\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x18\n" +
	"\avisible\x18\v \x01(\bR\avisible\x12\x1d\n" +
	"\n" +
	"sport_code\x18\f \x01(\tR\tsportCode\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12(\n" +
	"\x10google_icon_data\x18\x04 \x01(\tR\x0egoogleIconData\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtJ\x04\b\x02\x10\x03\"\x1c\n" +
	"\x1aListSportCategoriesRequest\"X\n" +
	"\x1bListSportCategoriesResponse\x129\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x19.catalog.v1.SportCategoryR\n" +
	"categories\")\n" +
	"\x17GetSportCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x11ListSportsRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"?\n" +
	"\x12ListSportsResponse\x12)\n" +
	"\x06sports\x18\x01 \x03(\v2\x11.catalog.v1.SportR\x06sports\"B\n" +
	"\x14SportAttributeOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x90\x02\n" +
	"\x13SportAttributeField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12:\n" +
	"\aoptions\x18\x05 \x03(\v2 .catalog.v1.SportAttributeOptionR\aoptions\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValue\x12#\n" +
	"\rdisplay_order\x18\a \x01(\x05R\fdisplayOrder\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"6\n" +
	"\x15GetSportSchemaRequest\x12\x1d\n" +
	"\n" +
	"sport_code\x18\x01 \x01(\tR\tsportCode\"p\n" +
	"\x16GetSportSchemaResponse\x12\x1d\n" +
	"\n" +
	"sport_code\x18\x01 \x01(\tR\tsportCode\x127\n" +
	"\x06fields\x18\x02 \x03(\v2\x1f.catalog.v1.SportAttributeFieldR\x06fields\"2\n" +
	"\bProvince\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"W\n" +
	"\bDistrict\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rprovince_code\x18\x02 \x01(\tR\fprovinceCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"S\n" +
	"\x04Ward\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rdistrict_code\x18\x02 \x01(\tR\fdistrictCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"*\n" +
	"\x14ListProvincesRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x15ListProvincesResponse\x122\n" +
	"\tprovinces\x18\x01 \x03(\v2\x14.catalog.v1.ProvinceR\tprovinces\"O\n" +
	"\x14ListDistrictsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rprovince_code\x18\x02 \x01(\tR\fprovinceCode\"K\n" +
	"\x15ListDistrictsResponse\x122\n" +
	"\tdistricts\x18\x01 \x03(\v2\x14.catalog.v1.DistrictR\tdistricts\"K\n" +
	"\x10ListWardsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rdistrict_code\x18\x02 \x01(\tR\fdistrictCode\";\n" +
	"\x11ListWardsResponse\x12&\n" +
	"\x05wards\x18\x01 \x03(\v2\x10.catalog.v1.WardR\x05wardsBEZCgithub.com/khoitran2003/sportinas-be-proto-gen/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_messages_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_messages_proto_rawDescData []byte
)

func file_catalog_v1_catalog_messages_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_messages_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_messages_proto_rawDesc), len(file_catalog_v1_catalog_messages_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_messages_proto_rawDescData
}

var file_catalog_v1_catalog_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_catalog_v1_catalog_messages_proto_goTypes = []any{
	(*SportCategory)(nil),               // 0: catalog.v1.SportCategory
	(*Sport)(nil),                       // 1: catalog.v1.Sport
	(*ListSportCategoriesRequest)(nil),  // 2: catalog.v1.ListSportCategoriesRequest
	(*ListSportCategoriesResponse)(nil), // 3: catalog.v1.ListSportCategoriesResponse
	(*GetSportCategoryRequest)(nil),     // 4: catalog.v1.GetSportCategoryRequest
	(*ListSportsRequest)(nil),           // 5: catalog.v1.ListSportsRequest
	(*ListSportsResponse)(nil),          // 6: catalog.v1.ListSportsResponse
	(*SportAttributeOption)(nil),        // 7: catalog.v1.SportAttributeOption
	(*SportAttributeField)(nil),         // 8: catalog.v1.SportAttributeField
	(*GetSportSchemaRequest)(nil),       // 9: catalog.v1.GetSportSchemaRequest
	(*GetSportSchemaResponse)(nil),      // 10: catalog.v1.GetSportSchemaResponse
	(*Province)(nil),                    // 11: catalog.v1.Province
	(*District)(nil),                    // 12: catalog.v1.District
	(*Ward)(nil),                        // 13: catalog.v1.Ward
	(*ListProvincesRequest)(nil),        // 14: catalog.v1.ListProvincesRequest
	(*ListProvincesResponse)(nil),       // 15: catalog.v1.ListProvincesResponse
	(*ListDistrictsRequest)(nil),        // 16: catalog.v1.ListDistrictsRequest
	(*ListDistrictsResponse)(nil),       // 17: catalog.v1.ListDistrictsResponse
	(*ListWardsRequest)(nil),            // 18: catalog.v1.ListWardsRequest
	(*ListWardsResponse)(nil),           // 19: catalog.v1.ListWardsResponse
	(*timestamppb.Timestamp)(nil),       // 20: google.protobuf.Timestamp
}
var file_catalog_v1_catalog_messages_proto_depIdxs = []int32{
	20, // 0: catalog.v1.SportCategory.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: catalog.v1.SportCategory.updated_at:type_name -> google.protobuf.Timestamp
	20, // 2: catalog.v1.Sport.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: catalog.v1.Sport.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: catalog.v1.ListSportCategoriesResponse.categories:type_name -> catalog.v1.SportCategory
	1,  // 5: catalog.v1.ListSportsResponse.sports:type_name -> catalog.v1.Sport
	7,  // 6: catalog.v1.SportAttributeField.options:type_name -> catalog.v1.SportAttributeOption
	8,  // 7: catalog.v1.GetSportSchemaResponse.fields:type_name -> catalog.v1.SportAttributeField
	11, // 8: catalog.v1.ListProvincesResponse.provinces:type_name -> catalog.v1.Province
	12, // 9: catalog.v1.ListDistrictsResponse.districts:type_name -> catalog.v1.District
	13, // 10: catalog.v1.ListWardsResponse.wards:type_name -> catalog.v1.Ward
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_messages_proto_init() }
func file_catalog_v1_catalog_messages_proto_init() {
	if File_catalog_v1_catalog_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_messages_proto_rawDesc), len(file_catalog_v1_catalog_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_v1_catalog_messages_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_messages_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_messages_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_messages_proto = out.File
	file_catalog_v1_catalog_messages_proto_goTypes = nil
	file_catalog_v1_catalog_messages_proto_depIdxs = nil
}
