// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/v1/facility_messages.proto

package catalogv1

import (
	v1 "github.com/Sportinas/be-proto-gen/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeoRef resolves administrative codes to display names (from public.provinces / districts / wards).
type GeoRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoRef) Reset() {
	*x = GeoRef{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoRef) ProtoMessage() {}

func (x *GeoRef) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoRef.ProtoReflect.Descriptor instead.
func (*GeoRef) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GeoRef) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GeoRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Facility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FacilityCode  string                 `protobuf:"bytes,2,opt,name=facility_code,json=facilityCode,proto3" json:"facility_code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Metadata      string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Amenities     []string               `protobuf:"bytes,8,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,13,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,15,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,16,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Images        []string               `protobuf:"bytes,17,rep,name=images,proto3" json:"images,omitempty"`
	// JSON string: { "monday": { "opening_time": "09:00:00", "closing_time": "21:00:00" }, ... }
	OperationTime string                 `protobuf:"bytes,18,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	Status        string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Province      *GeoRef                `protobuf:"bytes,22,opt,name=province,proto3" json:"province,omitempty"`
	District      *GeoRef                `protobuf:"bytes,23,opt,name=district,proto3" json:"district,omitempty"`
	Ward          *GeoRef                `protobuf:"bytes,24,opt,name=ward,proto3" json:"ward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facility) Reset() {
	*x = Facility{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facility) ProtoMessage() {}

func (x *Facility) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facility.ProtoReflect.Descriptor instead.
func (*Facility) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Facility) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Facility) GetFacilityCode() string {
	if x != nil {
		return x.FacilityCode
	}
	return ""
}

func (x *Facility) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Facility) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Facility) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Facility) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Facility) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Facility) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *Facility) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Facility) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Facility) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Facility) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Facility) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Facility) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Facility) GetOperationTime() string {
	if x != nil {
		return x.OperationTime
	}
	return ""
}

func (x *Facility) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Facility) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Facility) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Facility) GetProvince() *GeoRef {
	if x != nil {
		return x.Province
	}
	return nil
}

func (x *Facility) GetDistrict() *GeoRef {
	if x != nil {
		return x.District
	}
	return nil
}

func (x *Facility) GetWard() *GeoRef {
	if x != nil {
		return x.Ward
	}
	return nil
}

type CreateFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacilityCode  string                 `protobuf:"bytes,1,opt,name=facility_code,json=facilityCode,proto3" json:"facility_code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Amenities     []string               `protobuf:"bytes,7,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ProvinceCode  string                 `protobuf:"bytes,9,opt,name=province_code,json=provinceCode,proto3" json:"province_code,omitempty"`
	DistrictCode  string                 `protobuf:"bytes,10,opt,name=district_code,json=districtCode,proto3" json:"district_code,omitempty"`
	WardCode      string                 `protobuf:"bytes,11,opt,name=ward_code,json=wardCode,proto3" json:"ward_code,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,12,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,14,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,15,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Images        []string               `protobuf:"bytes,16,rep,name=images,proto3" json:"images,omitempty"`
	OperationTime string                 `protobuf:"bytes,17,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	Status        string                 `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFacilityRequest) Reset() {
	*x = CreateFacilityRequest{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFacilityRequest) ProtoMessage() {}

func (x *CreateFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFacilityRequest.ProtoReflect.Descriptor instead.
func (*CreateFacilityRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFacilityRequest) GetFacilityCode() string {
	if x != nil {
		return x.FacilityCode
	}
	return ""
}

func (x *CreateFacilityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFacilityRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateFacilityRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateFacilityRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateFacilityRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *CreateFacilityRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *CreateFacilityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFacilityRequest) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

func (x *CreateFacilityRequest) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

func (x *CreateFacilityRequest) GetWardCode() string {
	if x != nil {
		return x.WardCode
	}
	return ""
}

func (x *CreateFacilityRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateFacilityRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateFacilityRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CreateFacilityRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *CreateFacilityRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateFacilityRequest) GetOperationTime() string {
	if x != nil {
		return x.OperationTime
	}
	return ""
}

func (x *CreateFacilityRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFacilityResponse) Reset() {
	*x = CreateFacilityResponse{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFacilityResponse) ProtoMessage() {}

func (x *CreateFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFacilityResponse.ProtoReflect.Descriptor instead.
func (*CreateFacilityResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFacilityResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacilityRequest) Reset() {
	*x = GetFacilityRequest{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacilityRequest) ProtoMessage() {}

func (x *GetFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacilityRequest.ProtoReflect.Descriptor instead.
func (*GetFacilityRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetFacilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *Facility              `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacilityResponse) Reset() {
	*x = GetFacilityResponse{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacilityResponse) ProtoMessage() {}

func (x *GetFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacilityResponse.ProtoReflect.Descriptor instead.
func (*GetFacilityResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetFacilityResponse) GetFacility() *Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

type UpdateFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FacilityCode  *string                `protobuf:"bytes,13,opt,name=facility_code,json=facilityCode,proto3,oneof" json:"facility_code,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Address       *string                `protobuf:"bytes,3,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,4,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,5,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	Email         *string                `protobuf:"bytes,8,opt,name=email,proto3,oneof" json:"email,omitempty"`
	OperationTime *string                `protobuf:"bytes,9,opt,name=operation_time,json=operationTime,proto3,oneof" json:"operation_time,omitempty"`
	Status        *string                `protobuf:"bytes,10,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Amenities     []string               `protobuf:"bytes,11,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Images        []string               `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	// Geo codes from master data (same semantics as CreateFacilityRequest).
	ProvinceCode  *string `protobuf:"bytes,14,opt,name=province_code,json=provinceCode,proto3,oneof" json:"province_code,omitempty"`
	DistrictCode  *string `protobuf:"bytes,15,opt,name=district_code,json=districtCode,proto3,oneof" json:"district_code,omitempty"`
	WardCode      *string `protobuf:"bytes,16,opt,name=ward_code,json=wardCode,proto3,oneof" json:"ward_code,omitempty"`
	LogoUrl       *string `protobuf:"bytes,17,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	CoverImageUrl *string `protobuf:"bytes,18,opt,name=cover_image_url,json=coverImageUrl,proto3,oneof" json:"cover_image_url,omitempty"`
	Metadata      *string `protobuf:"bytes,19,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacilityRequest) Reset() {
	*x = UpdateFacilityRequest{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacilityRequest) ProtoMessage() {}

func (x *UpdateFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateFacilityRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFacilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFacilityRequest) GetFacilityCode() string {
	if x != nil && x.FacilityCode != nil {
		return *x.FacilityCode
	}
	return ""
}

func (x *UpdateFacilityRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateFacilityRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdateFacilityRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *UpdateFacilityRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateFacilityRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *UpdateFacilityRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateFacilityRequest) GetOperationTime() string {
	if x != nil && x.OperationTime != nil {
		return *x.OperationTime
	}
	return ""
}

func (x *UpdateFacilityRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateFacilityRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *UpdateFacilityRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateFacilityRequest) GetProvinceCode() string {
	if x != nil && x.ProvinceCode != nil {
		return *x.ProvinceCode
	}
	return ""
}

func (x *UpdateFacilityRequest) GetDistrictCode() string {
	if x != nil && x.DistrictCode != nil {
		return *x.DistrictCode
	}
	return ""
}

func (x *UpdateFacilityRequest) GetWardCode() string {
	if x != nil && x.WardCode != nil {
		return *x.WardCode
	}
	return ""
}

func (x *UpdateFacilityRequest) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

func (x *UpdateFacilityRequest) GetCoverImageUrl() string {
	if x != nil && x.CoverImageUrl != nil {
		return *x.CoverImageUrl
	}
	return ""
}

func (x *UpdateFacilityRequest) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

type UpdateFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *Facility              `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacilityResponse) Reset() {
	*x = UpdateFacilityResponse{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacilityResponse) ProtoMessage() {}

func (x *UpdateFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacilityResponse.ProtoReflect.Descriptor instead.
func (*UpdateFacilityResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFacilityResponse) GetFacility() *Facility {
	if x != nil {
		return x.Facility
	}
	return nil
}

type ListFacilitiesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ProvinceCode  string                    `protobuf:"bytes,1,opt,name=province_code,json=provinceCode,proto3" json:"province_code,omitempty"`
	DistrictCode  string                    `protobuf:"bytes,2,opt,name=district_code,json=districtCode,proto3" json:"district_code,omitempty"`
	Status        string                    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Pagination    *v1.PagePaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFacilitiesRequest) Reset() {
	*x = ListFacilitiesRequest{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFacilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFacilitiesRequest) ProtoMessage() {}

func (x *ListFacilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFacilitiesRequest.ProtoReflect.Descriptor instead.
func (*ListFacilitiesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ListFacilitiesRequest) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

func (x *ListFacilitiesRequest) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

func (x *ListFacilitiesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListFacilitiesRequest) GetPagination() *v1.PagePaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListFacilitiesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Facilities    []*Facility                `protobuf:"bytes,1,rep,name=facilities,proto3" json:"facilities,omitempty"`
	Meta          *v1.PagePaginationResponse `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFacilitiesResponse) Reset() {
	*x = ListFacilitiesResponse{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFacilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFacilitiesResponse) ProtoMessage() {}

func (x *ListFacilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFacilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListFacilitiesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ListFacilitiesResponse) GetFacilities() []*Facility {
	if x != nil {
		return x.Facilities
	}
	return nil
}

func (x *ListFacilitiesResponse) GetMeta() *v1.PagePaginationResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListPublicFacilitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ==========================================================
	// 1. TÌM KIẾM CƠ BẢN & VỊ TRÍ (Location & Keyword)
	// ==========================================================
	SearchTerm string `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"` // Tìm theo Tên sân, Địa chỉ (VD: "Chảo Lửa")
	// Lọc theo khu vực hành chính
	ProvinceCode string `protobuf:"bytes,2,opt,name=province_code,json=provinceCode,proto3" json:"province_code,omitempty"`
	DistrictCode string `protobuf:"bytes,3,opt,name=district_code,json=districtCode,proto3" json:"district_code,omitempty"`
	WardCode     string `protobuf:"bytes,4,opt,name=ward_code,json=wardCode,proto3" json:"ward_code,omitempty"`
	// (NÂNG CAO) Lọc theo GPS "Gần tôi" (Geospatial Search)
	UserLat    float64 `protobuf:"fixed64,5,opt,name=user_lat,json=userLat,proto3" json:"user_lat,omitempty"` // Tọa độ hiện tại của khách
	UserLng    float64 `protobuf:"fixed64,6,opt,name=user_lng,json=userLng,proto3" json:"user_lng,omitempty"`
	RadiusInKm float64 `protobuf:"fixed64,7,opt,name=radius_in_km,json=radiusInKm,proto3" json:"radius_in_km,omitempty"` // Bán kính tìm kiếm (VD: 5km, 10km)
	// ==========================================================
	// 2. BỘ LỌC TÀI NGUYÊN (Resource Filters) - Cốt lõi
	// ==========================================================
	ResourceType string `protobuf:"bytes,8,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // COURT, CLASS, COACH, EVENT
	SportCode    string `protobuf:"bytes,9,opt,name=sport_code,json=sportCode,proto3" json:"sport_code,omitempty"`          // VD: "1048" (Bóng đá)
	// JSON string chứa các đặc tính động của môn thể thao đó
	// (VD: "{\"format\": \"5v5\", \"has_roof\": true}")
	AttributesFilter string `protobuf:"bytes,10,opt,name=attributes_filter,json=attributesFilter,proto3" json:"attributes_filter,omitempty"`
	// ==========================================================
	// 3. THỜI GIAN & GIÁ CẢ (Availability & Pricing)
	// ==========================================================
	// Lọc xem sân có ĐANG TRỐNG vào ngày/giờ khách muốn không
	TargetDate string `protobuf:"bytes,11,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"` // VD: "2026-04-15"
	StartTime  string `protobuf:"bytes,12,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`    // VD: "17:00:00"
	EndTime    string `protobuf:"bytes,13,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`          // VD: "19:00:00"
	// Khoảng giá
	MinPrice float64 `protobuf:"fixed64,14,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"` // Giá thấp nhất
	MaxPrice float64 `protobuf:"fixed64,15,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"` // Giá cao nhất
	// ==========================================================
	// 4. BỘ LỌC CƠ SỞ VẬT CHẤT & ĐÁNH GIÁ (Facility Filters)
	// ==========================================================
	// Mảng các tiện ích khách yêu cầu (VD: ["FREE_WIFI", "PARKING_CAR"])
	Amenities []string `protobuf:"bytes,16,rep,name=amenities,proto3" json:"amenities,omitempty"`
	MinRating float32  `protobuf:"fixed32,17,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"` // Lọc sân từ 4 sao trở lên (VD: 4.0)
	// Kiểu sắp xếp (RECOMMENDED, DISTANCE, PRICE_ASC, PRICE_DESC, RATING)
	SortBy        string                      `protobuf:"bytes,19,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Pagination    *v1.CursorPaginationRequest `protobuf:"bytes,20,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicFacilitiesRequest) Reset() {
	*x = ListPublicFacilitiesRequest{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicFacilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicFacilitiesRequest) ProtoMessage() {}

func (x *ListPublicFacilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicFacilitiesRequest.ProtoReflect.Descriptor instead.
func (*ListPublicFacilitiesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ListPublicFacilitiesRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetProvinceCode() string {
	if x != nil {
		return x.ProvinceCode
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetDistrictCode() string {
	if x != nil {
		return x.DistrictCode
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetWardCode() string {
	if x != nil {
		return x.WardCode
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetUserLat() float64 {
	if x != nil {
		return x.UserLat
	}
	return 0
}

func (x *ListPublicFacilitiesRequest) GetUserLng() float64 {
	if x != nil {
		return x.UserLng
	}
	return 0
}

func (x *ListPublicFacilitiesRequest) GetRadiusInKm() float64 {
	if x != nil {
		return x.RadiusInKm
	}
	return 0
}

func (x *ListPublicFacilitiesRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetSportCode() string {
	if x != nil {
		return x.SportCode
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetAttributesFilter() string {
	if x != nil {
		return x.AttributesFilter
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ListPublicFacilitiesRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ListPublicFacilitiesRequest) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *ListPublicFacilitiesRequest) GetMinRating() float32 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *ListPublicFacilitiesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListPublicFacilitiesRequest) GetPagination() *v1.CursorPaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPublicFacilitiesResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Facilities    []*PublicFacility            `protobuf:"bytes,1,rep,name=facilities,proto3" json:"facilities,omitempty"`
	Meta          *v1.CursorPaginationResponse `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicFacilitiesResponse) Reset() {
	*x = ListPublicFacilitiesResponse{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicFacilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicFacilitiesResponse) ProtoMessage() {}

func (x *ListPublicFacilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicFacilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListPublicFacilitiesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ListPublicFacilitiesResponse) GetFacilities() []*PublicFacility {
	if x != nil {
		return x.Facilities
	}
	return nil
}

func (x *ListPublicFacilitiesResponse) GetMeta() *v1.CursorPaginationResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetDetailPublicFacilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailPublicFacilityRequest) Reset() {
	*x = GetDetailPublicFacilityRequest{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailPublicFacilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailPublicFacilityRequest) ProtoMessage() {}

func (x *GetDetailPublicFacilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailPublicFacilityRequest.ProtoReflect.Descriptor instead.
func (*GetDetailPublicFacilityRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{12}
}

func (x *GetDetailPublicFacilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDetailPublicFacilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facility      *PublicFacility        `protobuf:"bytes,1,opt,name=facility,proto3" json:"facility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailPublicFacilityResponse) Reset() {
	*x = GetDetailPublicFacilityResponse{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailPublicFacilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailPublicFacilityResponse) ProtoMessage() {}

func (x *GetDetailPublicFacilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailPublicFacilityResponse.ProtoReflect.Descriptor instead.
func (*GetDetailPublicFacilityResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GetDetailPublicFacilityResponse) GetFacility() *PublicFacility {
	if x != nil {
		return x.Facility
	}
	return nil
}

type PublicMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicMerchant) Reset() {
	*x = PublicMerchant{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicMerchant) ProtoMessage() {}

func (x *PublicMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicMerchant.ProtoReflect.Descriptor instead.
func (*PublicMerchant) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{14}
}

func (x *PublicMerchant) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublicMerchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PublicFacility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FacilityCode  string                 `protobuf:"bytes,2,opt,name=facility_code,json=facilityCode,proto3" json:"facility_code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Metadata      string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Amenities     []string               `protobuf:"bytes,8,rep,name=amenities,proto3" json:"amenities,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,13,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,15,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,16,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Images        []string               `protobuf:"bytes,17,rep,name=images,proto3" json:"images,omitempty"`
	OperationTime string                 `protobuf:"bytes,18,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	Status        string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	Province      *GeoRef                `protobuf:"bytes,22,opt,name=province,proto3" json:"province,omitempty"`
	District      *GeoRef                `protobuf:"bytes,23,opt,name=district,proto3" json:"district,omitempty"`
	Ward          *GeoRef                `protobuf:"bytes,24,opt,name=ward,proto3" json:"ward,omitempty"`
	Merchant      *PublicMerchant        `protobuf:"bytes,25,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicFacility) Reset() {
	*x = PublicFacility{}
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicFacility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicFacility) ProtoMessage() {}

func (x *PublicFacility) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_facility_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicFacility.ProtoReflect.Descriptor instead.
func (*PublicFacility) Descriptor() ([]byte, []int) {
	return file_catalog_v1_facility_messages_proto_rawDescGZIP(), []int{15}
}

func (x *PublicFacility) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicFacility) GetFacilityCode() string {
	if x != nil {
		return x.FacilityCode
	}
	return ""
}

func (x *PublicFacility) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicFacility) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PublicFacility) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PublicFacility) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PublicFacility) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *PublicFacility) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *PublicFacility) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublicFacility) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PublicFacility) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PublicFacility) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *PublicFacility) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *PublicFacility) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PublicFacility) GetOperationTime() string {
	if x != nil {
		return x.OperationTime
	}
	return ""
}

func (x *PublicFacility) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PublicFacility) GetProvince() *GeoRef {
	if x != nil {
		return x.Province
	}
	return nil
}

func (x *PublicFacility) GetDistrict() *GeoRef {
	if x != nil {
		return x.District
	}
	return nil
}

func (x *PublicFacility) GetWard() *GeoRef {
	if x != nil {
		return x.Ward
	}
	return nil
}

func (x *PublicFacility) GetMerchant() *PublicMerchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

var File_catalog_v1_facility_messages_proto protoreflect.FileDescriptor

const file_catalog_v1_facility_messages_proto_rawDesc = "" +
	"\n" +
	"\"catalog/v1/facility_messages.proto\x12\n" +
	"catalog.v1\x1a\x1acommon/v1/pagination.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x06GeoRef\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe6\x05\n" +
	"\bFacility\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rfacility_code\x18\x02 \x01(\tR\ffacilityCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\x12\x1c\n" +
	"\tamenities\x18\b \x03(\tR\tamenities\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12!\n" +
	"\fphone_number\x18\r \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x0e \x01(\tR\x05email\x12\x19\n" +
	"\blogo_url\x18\x0f \x01(\tR\alogoUrl\x12&\n" +
	"\x0fcover_image_url\x18\x10 \x01(\tR\rcoverImageUrl\x12\x16\n" +
	"\x06images\x18\x11 \x03(\tR\x06images\x12%\n" +
	"\x0eoperation_time\x18\x12 \x01(\tR\roperationTime\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12.\n" +
	"\bprovince\x18\x16 \x01(\v2\x12.catalog.v1.GeoRefR\bprovince\x12.\n" +
	"\bdistrict\x18\x17 \x01(\v2\x12.catalog.v1.GeoRefR\bdistrict\x12&\n" +
	"\x04ward\x18\x18 \x01(\v2\x12.catalog.v1.GeoRefR\x04wardJ\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\r\"\xba\x04\n" +
	"\x15CreateFacilityRequest\x12#\n" +
	"\rfacility_code\x18\x01 \x01(\tR\ffacilityCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x12\x1c\n" +
	"\tamenities\x18\a \x03(\tR\tamenities\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12#\n" +
	"\rprovince_code\x18\t \x01(\tR\fprovinceCode\x12#\n" +
	"\rdistrict_code\x18\n" +
	" \x01(\tR\fdistrictCode\x12\x1b\n" +
	"\tward_code\x18\v \x01(\tR\bwardCode\x12!\n" +
	"\fphone_number\x18\f \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\r \x01(\tR\x05email\x12\x19\n" +
	"\blogo_url\x18\x0e \x01(\tR\alogoUrl\x12&\n" +
	"\x0fcover_image_url\x18\x0f \x01(\tR\rcoverImageUrl\x12\x16\n" +
	"\x06images\x18\x10 \x03(\tR\x06images\x12%\n" +
	"\x0eoperation_time\x18\x11 \x01(\tR\roperationTime\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\"(\n" +
	"\x16CreateFacilityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12GetFacilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x13GetFacilityResponse\x120\n" +
	"\bfacility\x18\x01 \x01(\v2\x14.catalog.v1.FacilityR\bfacility\"\x85\a\n" +
	"\x15UpdateFacilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\rfacility_code\x18\r \x01(\tH\x00R\ffacilityCode\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x03 \x01(\tH\x02R\aaddress\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\x04 \x01(\x01H\x03R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x05 \x01(\x01H\x04R\tlongitude\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x05R\vdescription\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\a \x01(\tH\x06R\vphoneNumber\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\b \x01(\tH\aR\x05email\x88\x01\x01\x12*\n" +
	"\x0eoperation_time\x18\t \x01(\tH\bR\roperationTime\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\n" +
	" \x01(\tH\tR\x06status\x88\x01\x01\x12\x1c\n" +
	"\tamenities\x18\v \x03(\tR\tamenities\x12\x16\n" +
	"\x06images\x18\f \x03(\tR\x06images\x12(\n" +
	"\rprovince_code\x18\x0e \x01(\tH\n" +
	"R\fprovinceCode\x88\x01\x01\x12(\n" +
	"\rdistrict_code\x18\x0f \x01(\tH\vR\fdistrictCode\x88\x01\x01\x12 \n" +
	"\tward_code\x18\x10 \x01(\tH\fR\bwardCode\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\x11 \x01(\tH\rR\alogoUrl\x88\x01\x01\x12+\n" +
	"\x0fcover_image_url\x18\x12 \x01(\tH\x0eR\rcoverImageUrl\x88\x01\x01\x12\x1f\n" +
	"\bmetadata\x18\x13 \x01(\tH\x0fR\bmetadata\x88\x01\x01B\x10\n" +
	"\x0e_facility_codeB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_addressB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_phone_numberB\b\n" +
	"\x06_emailB\x11\n" +
	"\x0f_operation_timeB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_province_codeB\x10\n" +
	"\x0e_district_codeB\f\n" +
	"\n" +
	"_ward_codeB\v\n" +
	"\t_logo_urlB\x12\n" +
	"\x10_cover_image_urlB\v\n" +
	"\t_metadata\"J\n" +
	"\x16UpdateFacilityResponse\x120\n" +
	"\bfacility\x18\x01 \x01(\v2\x14.catalog.v1.FacilityR\bfacility\"\xbb\x01\n" +
	"\x15ListFacilitiesRequest\x12#\n" +
	"\rprovince_code\x18\x01 \x01(\tR\fprovinceCode\x12#\n" +
	"\rdistrict_code\x18\x02 \x01(\tR\fdistrictCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12@\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2 .common.v1.PagePaginationRequestR\n" +
	"pagination\"\x85\x01\n" +
	"\x16ListFacilitiesResponse\x124\n" +
	"\n" +
	"facilities\x18\x01 \x03(\v2\x14.catalog.v1.FacilityR\n" +
	"facilities\x125\n" +
	"\x04meta\x18\x02 \x01(\v2!.common.v1.PagePaginationResponseR\x04meta\"\x9d\x05\n" +
	"\x1bListPublicFacilitiesRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\x12#\n" +
	"\rprovince_code\x18\x02 \x01(\tR\fprovinceCode\x12#\n" +
	"\rdistrict_code\x18\x03 \x01(\tR\fdistrictCode\x12\x1b\n" +
	"\tward_code\x18\x04 \x01(\tR\bwardCode\x12\x19\n" +
	"\buser_lat\x18\x05 \x01(\x01R\auserLat\x12\x19\n" +
	"\buser_lng\x18\x06 \x01(\x01R\auserLng\x12 \n" +
	"\fradius_in_km\x18\a \x01(\x01R\n" +
	"radiusInKm\x12#\n" +
	"\rresource_type\x18\b \x01(\tR\fresourceType\x12\x1d\n" +
	"\n" +
	"sport_code\x18\t \x01(\tR\tsportCode\x12+\n" +
	"\x11attributes_filter\x18\n" +
	" \x01(\tR\x10attributesFilter\x12\x1f\n" +
	"\vtarget_date\x18\v \x01(\tR\n" +
	"targetDate\x12\x1d\n" +
	"\n" +
	"start_time\x18\f \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\r \x01(\tR\aendTime\x12\x1b\n" +
	"\tmin_price\x18\x0e \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x0f \x01(\x01R\bmaxPrice\x12\x1c\n" +
	"\tamenities\x18\x10 \x03(\tR\tamenities\x12\x1d\n" +
	"\n" +
	"min_rating\x18\x11 \x01(\x02R\tminRating\x12\x17\n" +
	"\asort_by\x18\x13 \x01(\tR\x06sortBy\x12B\n" +
	"\n" +
	"pagination\x18\x14 \x01(\v2\".common.v1.CursorPaginationRequestR\n" +
	"pagination\"\x93\x01\n" +
	"\x1cListPublicFacilitiesResponse\x12:\n" +
	"\n" +
	"facilities\x18\x01 \x03(\v2\x1a.catalog.v1.PublicFacilityR\n" +
	"facilities\x127\n" +
	"\x04meta\x18\x02 \x01(\v2#.common.v1.CursorPaginationResponseR\x04meta\"0\n" +
	"\x1eGetDetailPublicFacilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x1fGetDetailPublicFacilityResponse\x126\n" +
	"\bfacility\x18\x01 \x01(\v2\x1a.catalog.v1.PublicFacilityR\bfacility\"6\n" +
	"\x0ePublicMerchant\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xae\x05\n" +
	"\x0ePublicFacility\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rfacility_code\x18\x02 \x01(\tR\ffacilityCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\x12\x1c\n" +
	"\tamenities\x18\b \x03(\tR\tamenities\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12!\n" +
	"\fphone_number\x18\r \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x0e \x01(\tR\x05email\x12\x19\n" +
	"\blogo_url\x18\x0f \x01(\tR\alogoUrl\x12&\n" +
	"\x0fcover_image_url\x18\x10 \x01(\tR\rcoverImageUrl\x12\x16\n" +
	"\x06images\x18\x11 \x03(\tR\x06images\x12%\n" +
	"\x0eoperation_time\x18\x12 \x01(\tR\roperationTime\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\x12.\n" +
	"\bprovince\x18\x16 \x01(\v2\x12.catalog.v1.GeoRefR\bprovince\x12.\n" +
	"\bdistrict\x18\x17 \x01(\v2\x12.catalog.v1.GeoRefR\bdistrict\x12&\n" +
	"\x04ward\x18\x18 \x01(\v2\x12.catalog.v1.GeoRefR\x04ward\x126\n" +
	"\bmerchant\x18\x19 \x01(\v2\x1a.catalog.v1.PublicMerchantR\bmerchantJ\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rB8Z6github.com/Sportinas/be-proto-gen/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_facility_messages_proto_rawDescOnce sync.Once
	file_catalog_v1_facility_messages_proto_rawDescData []byte
)

func file_catalog_v1_facility_messages_proto_rawDescGZIP() []byte {
	file_catalog_v1_facility_messages_proto_rawDescOnce.Do(func() {
		file_catalog_v1_facility_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_facility_messages_proto_rawDesc), len(file_catalog_v1_facility_messages_proto_rawDesc)))
	})
	return file_catalog_v1_facility_messages_proto_rawDescData
}

var file_catalog_v1_facility_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_catalog_v1_facility_messages_proto_goTypes = []any{
	(*GeoRef)(nil),                          // 0: catalog.v1.GeoRef
	(*Facility)(nil),                        // 1: catalog.v1.Facility
	(*CreateFacilityRequest)(nil),           // 2: catalog.v1.CreateFacilityRequest
	(*CreateFacilityResponse)(nil),          // 3: catalog.v1.CreateFacilityResponse
	(*GetFacilityRequest)(nil),              // 4: catalog.v1.GetFacilityRequest
	(*GetFacilityResponse)(nil),             // 5: catalog.v1.GetFacilityResponse
	(*UpdateFacilityRequest)(nil),           // 6: catalog.v1.UpdateFacilityRequest
	(*UpdateFacilityResponse)(nil),          // 7: catalog.v1.UpdateFacilityResponse
	(*ListFacilitiesRequest)(nil),           // 8: catalog.v1.ListFacilitiesRequest
	(*ListFacilitiesResponse)(nil),          // 9: catalog.v1.ListFacilitiesResponse
	(*ListPublicFacilitiesRequest)(nil),     // 10: catalog.v1.ListPublicFacilitiesRequest
	(*ListPublicFacilitiesResponse)(nil),    // 11: catalog.v1.ListPublicFacilitiesResponse
	(*GetDetailPublicFacilityRequest)(nil),  // 12: catalog.v1.GetDetailPublicFacilityRequest
	(*GetDetailPublicFacilityResponse)(nil), // 13: catalog.v1.GetDetailPublicFacilityResponse
	(*PublicMerchant)(nil),                  // 14: catalog.v1.PublicMerchant
	(*PublicFacility)(nil),                  // 15: catalog.v1.PublicFacility
	(*timestamppb.Timestamp)(nil),           // 16: google.protobuf.Timestamp
	(*v1.PagePaginationRequest)(nil),        // 17: common.v1.PagePaginationRequest
	(*v1.PagePaginationResponse)(nil),       // 18: common.v1.PagePaginationResponse
	(*v1.CursorPaginationRequest)(nil),      // 19: common.v1.CursorPaginationRequest
	(*v1.CursorPaginationResponse)(nil),     // 20: common.v1.CursorPaginationResponse
}
var file_catalog_v1_facility_messages_proto_depIdxs = []int32{
	16, // 0: catalog.v1.Facility.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: catalog.v1.Facility.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: catalog.v1.Facility.province:type_name -> catalog.v1.GeoRef
	0,  // 3: catalog.v1.Facility.district:type_name -> catalog.v1.GeoRef
	0,  // 4: catalog.v1.Facility.ward:type_name -> catalog.v1.GeoRef
	1,  // 5: catalog.v1.GetFacilityResponse.facility:type_name -> catalog.v1.Facility
	1,  // 6: catalog.v1.UpdateFacilityResponse.facility:type_name -> catalog.v1.Facility
	17, // 7: catalog.v1.ListFacilitiesRequest.pagination:type_name -> common.v1.PagePaginationRequest
	1,  // 8: catalog.v1.ListFacilitiesResponse.facilities:type_name -> catalog.v1.Facility
	18, // 9: catalog.v1.ListFacilitiesResponse.meta:type_name -> common.v1.PagePaginationResponse
	19, // 10: catalog.v1.ListPublicFacilitiesRequest.pagination:type_name -> common.v1.CursorPaginationRequest
	15, // 11: catalog.v1.ListPublicFacilitiesResponse.facilities:type_name -> catalog.v1.PublicFacility
	20, // 12: catalog.v1.ListPublicFacilitiesResponse.meta:type_name -> common.v1.CursorPaginationResponse
	15, // 13: catalog.v1.GetDetailPublicFacilityResponse.facility:type_name -> catalog.v1.PublicFacility
	0,  // 14: catalog.v1.PublicFacility.province:type_name -> catalog.v1.GeoRef
	0,  // 15: catalog.v1.PublicFacility.district:type_name -> catalog.v1.GeoRef
	0,  // 16: catalog.v1.PublicFacility.ward:type_name -> catalog.v1.GeoRef
	14, // 17: catalog.v1.PublicFacility.merchant:type_name -> catalog.v1.PublicMerchant
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_catalog_v1_facility_messages_proto_init() }
func file_catalog_v1_facility_messages_proto_init() {
	if File_catalog_v1_facility_messages_proto != nil {
		return
	}
	file_catalog_v1_facility_messages_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_facility_messages_proto_rawDesc), len(file_catalog_v1_facility_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_v1_facility_messages_proto_goTypes,
		DependencyIndexes: file_catalog_v1_facility_messages_proto_depIdxs,
		MessageInfos:      file_catalog_v1_facility_messages_proto_msgTypes,
	}.Build()
	File_catalog_v1_facility_messages_proto = out.File
	file_catalog_v1_facility_messages_proto_goTypes = nil
	file_catalog_v1_facility_messages_proto_depIdxs = nil
}
