// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/v1/merchant_service.proto

package catalogv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_catalog_v1_merchant_service_proto protoreflect.FileDescriptor

const file_catalog_v1_merchant_service_proto_rawDesc = "" +
	"\n" +
	"!catalog/v1/merchant_service.proto\x12\n" +
	"catalog.v1\x1a\"catalog/v1/facility_messages.proto\x1a\"catalog/v1/resource_messages.proto\x1a!catalog/v1/pricing_messages.proto\x1a\x1cgoogle/api/annotations.proto2\x9e\x04\n" +
	"\x17MerchantFacilityService\x12\x80\x01\n" +
	"\x0eCreateFacility\x12!.catalog.v1.CreateFacilityRequest\x1a\".catalog.v1.CreateFacilityResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/merchants/facilities\x12y\n" +
	"\vGetFacility\x12\x1e.catalog.v1.GetFacilityRequest\x1a\x1f.catalog.v1.GetFacilityResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/merchants/facilities/{id}\x12\x85\x01\n" +
	"\x0eUpdateFacility\x12!.catalog.v1.UpdateFacilityRequest\x1a\".catalog.v1.UpdateFacilityResponse\",\x82\xd3\xe4\x93\x02&:\x01*2!/api/v1/merchants/facilities/{id}\x12}\n" +
	"\x0eListFacilities\x12!.catalog.v1.ListFacilitiesRequest\x1a\".catalog.v1.ListFacilitiesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/merchants/facilities2\x85\f\n" +
	"\x17MerchantResourceService\x12\x8a\x01\n" +
	"\x0eCreateResource\x12!.catalog.v1.CreateResourceRequest\x1a\".catalog.v1.CreateResourceResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/merchants/facilities/resources\x12\xb0\x01\n" +
	"\x17ListResourcesByFacility\x12*.catalog.v1.ListResourcesByFacilityRequest\x1a+.catalog.v1.ListResourcesByFacilityResponse\"<\x82\xd3\xe4\x93\x026\x124/api/v1/merchants/facilities/{facility_id}/resources\x12\x8c\x01\n" +
	"\vGetResource\x12\x1e.catalog.v1.GetResourceRequest\x1a\x1f.catalog.v1.GetResourceResponse\"<\x82\xd3\xe4\x93\x026\x124/api/v1/merchants/facilities/resources/{resource_id}\x12\x98\x01\n" +
	"\x0eUpdateResource\x12!.catalog.v1.UpdateResourceRequest\x1a\".catalog.v1.UpdateResourceResponse\"?\x82\xd3\xe4\x93\x029:\x01*24/api/v1/merchants/facilities/resources/{resource_id}\x12\xb8\x01\n" +
	"\x13UpdateChildResource\x12&.catalog.v1.UpdateChildResourceRequest\x1a'.catalog.v1.UpdateChildResourceResponse\"P\x82\xd3\xe4\x93\x02J:\x01*2E/api/v1/merchants/facilities/resources/{resource_id}/child/{child_id}\x12\xbd\x01\n" +
	"\x1aListPricingRulesByResource\x12-.catalog.v1.ListPricingRulesByResourceRequest\x1a$.catalog.v1.ListPricingRulesResponse\"J\x82\xd3\xe4\x93\x02D\x12B/api/v1/merchants/facilities/resources/{resource_id}/pricing-rules\x12\xaf\x01\n" +
	"\x11CreatePricingRule\x12$.catalog.v1.CreatePricingRuleRequest\x1a%.catalog.v1.CreatePricingRuleResponse\"M\x82\xd3\xe4\x93\x02G:\x01*\"B/api/v1/merchants/facilities/resources/{resource_id}/pricing-rules\x12\xa9\x01\n" +
	"\x11UpdatePricingRule\x12$.catalog.v1.UpdatePricingRuleRequest\x1a%.catalog.v1.UpdatePricingRuleResponse\"G\x82\xd3\xe4\x93\x02A:\x01*2</api/v1/merchants/facilities/pricing-rules/{pricing_rule_id}\x12\xa6\x01\n" +
	"\x11DeletePricingRule\x12$.catalog.v1.DeletePricingRuleRequest\x1a%.catalog.v1.DeletePricingRuleResponse\"D\x82\xd3\xe4\x93\x02>*</api/v1/merchants/facilities/pricing-rules/{pricing_rule_id}BEZCgithub.com/khoitran2003/sportinas-be-proto-gen/catalog/v1;catalogv1b\x06proto3"

var file_catalog_v1_merchant_service_proto_goTypes = []any{
	(*CreateFacilityRequest)(nil),             // 0: catalog.v1.CreateFacilityRequest
	(*GetFacilityRequest)(nil),                // 1: catalog.v1.GetFacilityRequest
	(*UpdateFacilityRequest)(nil),             // 2: catalog.v1.UpdateFacilityRequest
	(*ListFacilitiesRequest)(nil),             // 3: catalog.v1.ListFacilitiesRequest
	(*CreateResourceRequest)(nil),             // 4: catalog.v1.CreateResourceRequest
	(*ListResourcesByFacilityRequest)(nil),    // 5: catalog.v1.ListResourcesByFacilityRequest
	(*GetResourceRequest)(nil),                // 6: catalog.v1.GetResourceRequest
	(*UpdateResourceRequest)(nil),             // 7: catalog.v1.UpdateResourceRequest
	(*UpdateChildResourceRequest)(nil),        // 8: catalog.v1.UpdateChildResourceRequest
	(*ListPricingRulesByResourceRequest)(nil), // 9: catalog.v1.ListPricingRulesByResourceRequest
	(*CreatePricingRuleRequest)(nil),          // 10: catalog.v1.CreatePricingRuleRequest
	(*UpdatePricingRuleRequest)(nil),          // 11: catalog.v1.UpdatePricingRuleRequest
	(*DeletePricingRuleRequest)(nil),          // 12: catalog.v1.DeletePricingRuleRequest
	(*CreateFacilityResponse)(nil),            // 13: catalog.v1.CreateFacilityResponse
	(*GetFacilityResponse)(nil),               // 14: catalog.v1.GetFacilityResponse
	(*UpdateFacilityResponse)(nil),            // 15: catalog.v1.UpdateFacilityResponse
	(*ListFacilitiesResponse)(nil),            // 16: catalog.v1.ListFacilitiesResponse
	(*CreateResourceResponse)(nil),            // 17: catalog.v1.CreateResourceResponse
	(*ListResourcesByFacilityResponse)(nil),   // 18: catalog.v1.ListResourcesByFacilityResponse
	(*GetResourceResponse)(nil),               // 19: catalog.v1.GetResourceResponse
	(*UpdateResourceResponse)(nil),            // 20: catalog.v1.UpdateResourceResponse
	(*UpdateChildResourceResponse)(nil),       // 21: catalog.v1.UpdateChildResourceResponse
	(*ListPricingRulesResponse)(nil),          // 22: catalog.v1.ListPricingRulesResponse
	(*CreatePricingRuleResponse)(nil),         // 23: catalog.v1.CreatePricingRuleResponse
	(*UpdatePricingRuleResponse)(nil),         // 24: catalog.v1.UpdatePricingRuleResponse
	(*DeletePricingRuleResponse)(nil),         // 25: catalog.v1.DeletePricingRuleResponse
}
var file_catalog_v1_merchant_service_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.MerchantFacilityService.CreateFacility:input_type -> catalog.v1.CreateFacilityRequest
	1,  // 1: catalog.v1.MerchantFacilityService.GetFacility:input_type -> catalog.v1.GetFacilityRequest
	2,  // 2: catalog.v1.MerchantFacilityService.UpdateFacility:input_type -> catalog.v1.UpdateFacilityRequest
	3,  // 3: catalog.v1.MerchantFacilityService.ListFacilities:input_type -> catalog.v1.ListFacilitiesRequest
	4,  // 4: catalog.v1.MerchantResourceService.CreateResource:input_type -> catalog.v1.CreateResourceRequest
	5,  // 5: catalog.v1.MerchantResourceService.ListResourcesByFacility:input_type -> catalog.v1.ListResourcesByFacilityRequest
	6,  // 6: catalog.v1.MerchantResourceService.GetResource:input_type -> catalog.v1.GetResourceRequest
	7,  // 7: catalog.v1.MerchantResourceService.UpdateResource:input_type -> catalog.v1.UpdateResourceRequest
	8,  // 8: catalog.v1.MerchantResourceService.UpdateChildResource:input_type -> catalog.v1.UpdateChildResourceRequest
	9,  // 9: catalog.v1.MerchantResourceService.ListPricingRulesByResource:input_type -> catalog.v1.ListPricingRulesByResourceRequest
	10, // 10: catalog.v1.MerchantResourceService.CreatePricingRule:input_type -> catalog.v1.CreatePricingRuleRequest
	11, // 11: catalog.v1.MerchantResourceService.UpdatePricingRule:input_type -> catalog.v1.UpdatePricingRuleRequest
	12, // 12: catalog.v1.MerchantResourceService.DeletePricingRule:input_type -> catalog.v1.DeletePricingRuleRequest
	13, // 13: catalog.v1.MerchantFacilityService.CreateFacility:output_type -> catalog.v1.CreateFacilityResponse
	14, // 14: catalog.v1.MerchantFacilityService.GetFacility:output_type -> catalog.v1.GetFacilityResponse
	15, // 15: catalog.v1.MerchantFacilityService.UpdateFacility:output_type -> catalog.v1.UpdateFacilityResponse
	16, // 16: catalog.v1.MerchantFacilityService.ListFacilities:output_type -> catalog.v1.ListFacilitiesResponse
	17, // 17: catalog.v1.MerchantResourceService.CreateResource:output_type -> catalog.v1.CreateResourceResponse
	18, // 18: catalog.v1.MerchantResourceService.ListResourcesByFacility:output_type -> catalog.v1.ListResourcesByFacilityResponse
	19, // 19: catalog.v1.MerchantResourceService.GetResource:output_type -> catalog.v1.GetResourceResponse
	20, // 20: catalog.v1.MerchantResourceService.UpdateResource:output_type -> catalog.v1.UpdateResourceResponse
	21, // 21: catalog.v1.MerchantResourceService.UpdateChildResource:output_type -> catalog.v1.UpdateChildResourceResponse
	22, // 22: catalog.v1.MerchantResourceService.ListPricingRulesByResource:output_type -> catalog.v1.ListPricingRulesResponse
	23, // 23: catalog.v1.MerchantResourceService.CreatePricingRule:output_type -> catalog.v1.CreatePricingRuleResponse
	24, // 24: catalog.v1.MerchantResourceService.UpdatePricingRule:output_type -> catalog.v1.UpdatePricingRuleResponse
	25, // 25: catalog.v1.MerchantResourceService.DeletePricingRule:output_type -> catalog.v1.DeletePricingRuleResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_v1_merchant_service_proto_init() }
func file_catalog_v1_merchant_service_proto_init() {
	if File_catalog_v1_merchant_service_proto != nil {
		return
	}
	file_catalog_v1_facility_messages_proto_init()
	file_catalog_v1_resource_messages_proto_init()
	file_catalog_v1_pricing_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_merchant_service_proto_rawDesc), len(file_catalog_v1_merchant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_catalog_v1_merchant_service_proto_goTypes,
		DependencyIndexes: file_catalog_v1_merchant_service_proto_depIdxs,
	}.Build()
	File_catalog_v1_merchant_service_proto = out.File
	file_catalog_v1_merchant_service_proto_goTypes = nil
	file_catalog_v1_merchant_service_proto_depIdxs = nil
}
