// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: catalog/v1/merchant_service.proto

package catalogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantFacilityService_CreateFacility_FullMethodName = "/catalog.v1.MerchantFacilityService/CreateFacility"
	MerchantFacilityService_GetFacility_FullMethodName    = "/catalog.v1.MerchantFacilityService/GetFacility"
	MerchantFacilityService_UpdateFacility_FullMethodName = "/catalog.v1.MerchantFacilityService/UpdateFacility"
	MerchantFacilityService_ListFacilities_FullMethodName = "/catalog.v1.MerchantFacilityService/ListFacilities"
)

// MerchantFacilityServiceClient is the client API for MerchantFacilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MerchantFacilityService — API chủ sân (admin gateway / JWT).
type MerchantFacilityServiceClient interface {
	CreateFacility(ctx context.Context, in *CreateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityResponse, error)
	GetFacility(ctx context.Context, in *GetFacilityRequest, opts ...grpc.CallOption) (*GetFacilityResponse, error)
	UpdateFacility(ctx context.Context, in *UpdateFacilityRequest, opts ...grpc.CallOption) (*UpdateFacilityResponse, error)
	ListFacilities(ctx context.Context, in *ListFacilitiesRequest, opts ...grpc.CallOption) (*ListFacilitiesResponse, error)
}

type merchantFacilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantFacilityServiceClient(cc grpc.ClientConnInterface) MerchantFacilityServiceClient {
	return &merchantFacilityServiceClient{cc}
}

func (c *merchantFacilityServiceClient) CreateFacility(ctx context.Context, in *CreateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFacilityResponse)
	err := c.cc.Invoke(ctx, MerchantFacilityService_CreateFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantFacilityServiceClient) GetFacility(ctx context.Context, in *GetFacilityRequest, opts ...grpc.CallOption) (*GetFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFacilityResponse)
	err := c.cc.Invoke(ctx, MerchantFacilityService_GetFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantFacilityServiceClient) UpdateFacility(ctx context.Context, in *UpdateFacilityRequest, opts ...grpc.CallOption) (*UpdateFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFacilityResponse)
	err := c.cc.Invoke(ctx, MerchantFacilityService_UpdateFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantFacilityServiceClient) ListFacilities(ctx context.Context, in *ListFacilitiesRequest, opts ...grpc.CallOption) (*ListFacilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFacilitiesResponse)
	err := c.cc.Invoke(ctx, MerchantFacilityService_ListFacilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantFacilityServiceServer is the server API for MerchantFacilityService service.
// All implementations should embed UnimplementedMerchantFacilityServiceServer
// for forward compatibility.
//
// MerchantFacilityService — API chủ sân (admin gateway / JWT).
type MerchantFacilityServiceServer interface {
	CreateFacility(context.Context, *CreateFacilityRequest) (*CreateFacilityResponse, error)
	GetFacility(context.Context, *GetFacilityRequest) (*GetFacilityResponse, error)
	UpdateFacility(context.Context, *UpdateFacilityRequest) (*UpdateFacilityResponse, error)
	ListFacilities(context.Context, *ListFacilitiesRequest) (*ListFacilitiesResponse, error)
}

// UnimplementedMerchantFacilityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantFacilityServiceServer struct{}

func (UnimplementedMerchantFacilityServiceServer) CreateFacility(context.Context, *CreateFacilityRequest) (*CreateFacilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFacility not implemented")
}
func (UnimplementedMerchantFacilityServiceServer) GetFacility(context.Context, *GetFacilityRequest) (*GetFacilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFacility not implemented")
}
func (UnimplementedMerchantFacilityServiceServer) UpdateFacility(context.Context, *UpdateFacilityRequest) (*UpdateFacilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFacility not implemented")
}
func (UnimplementedMerchantFacilityServiceServer) ListFacilities(context.Context, *ListFacilitiesRequest) (*ListFacilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFacilities not implemented")
}
func (UnimplementedMerchantFacilityServiceServer) testEmbeddedByValue() {}

// UnsafeMerchantFacilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantFacilityServiceServer will
// result in compilation errors.
type UnsafeMerchantFacilityServiceServer interface {
	mustEmbedUnimplementedMerchantFacilityServiceServer()
}

func RegisterMerchantFacilityServiceServer(s grpc.ServiceRegistrar, srv MerchantFacilityServiceServer) {
	// If the following call panics, it indicates UnimplementedMerchantFacilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantFacilityService_ServiceDesc, srv)
}

func _MerchantFacilityService_CreateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantFacilityServiceServer).CreateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantFacilityService_CreateFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantFacilityServiceServer).CreateFacility(ctx, req.(*CreateFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantFacilityService_GetFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantFacilityServiceServer).GetFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantFacilityService_GetFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantFacilityServiceServer).GetFacility(ctx, req.(*GetFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantFacilityService_UpdateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantFacilityServiceServer).UpdateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantFacilityService_UpdateFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantFacilityServiceServer).UpdateFacility(ctx, req.(*UpdateFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantFacilityService_ListFacilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFacilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantFacilityServiceServer).ListFacilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantFacilityService_ListFacilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantFacilityServiceServer).ListFacilities(ctx, req.(*ListFacilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantFacilityService_ServiceDesc is the grpc.ServiceDesc for MerchantFacilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantFacilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.MerchantFacilityService",
	HandlerType: (*MerchantFacilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFacility",
			Handler:    _MerchantFacilityService_CreateFacility_Handler,
		},
		{
			MethodName: "GetFacility",
			Handler:    _MerchantFacilityService_GetFacility_Handler,
		},
		{
			MethodName: "UpdateFacility",
			Handler:    _MerchantFacilityService_UpdateFacility_Handler,
		},
		{
			MethodName: "ListFacilities",
			Handler:    _MerchantFacilityService_ListFacilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog/v1/merchant_service.proto",
}

const (
	MerchantResourceService_CreateResource_FullMethodName             = "/catalog.v1.MerchantResourceService/CreateResource"
	MerchantResourceService_ListResourcesByFacility_FullMethodName    = "/catalog.v1.MerchantResourceService/ListResourcesByFacility"
	MerchantResourceService_GetResource_FullMethodName                = "/catalog.v1.MerchantResourceService/GetResource"
	MerchantResourceService_UpdateResource_FullMethodName             = "/catalog.v1.MerchantResourceService/UpdateResource"
	MerchantResourceService_UpdateChildResource_FullMethodName        = "/catalog.v1.MerchantResourceService/UpdateChildResource"
	MerchantResourceService_ListPricingRulesByResource_FullMethodName = "/catalog.v1.MerchantResourceService/ListPricingRulesByResource"
	MerchantResourceService_CreatePricingRule_FullMethodName          = "/catalog.v1.MerchantResourceService/CreatePricingRule"
	MerchantResourceService_UpdatePricingRule_FullMethodName          = "/catalog.v1.MerchantResourceService/UpdatePricingRule"
	MerchantResourceService_DeletePricingRule_FullMethodName          = "/catalog.v1.MerchantResourceService/DeletePricingRule"
)

// MerchantResourceServiceClient is the client API for MerchantResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantResourceServiceClient interface {
	// API Tạo Sân con nằm trong Cơ sở
	CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error)
	// Danh sách resource theo facility (facility_id trong path để tránh trùng với resource_id).
	ListResourcesByFacility(ctx context.Context, in *ListResourcesByFacilityRequest, opts ...grpc.CallOption) (*ListResourcesByFacilityResponse, error)
	GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error)
	UpdateResource(ctx context.Context, in *UpdateResourceRequest, opts ...grpc.CallOption) (*UpdateResourceResponse, error)
	UpdateChildResource(ctx context.Context, in *UpdateChildResourceRequest, opts ...grpc.CallOption) (*UpdateChildResourceResponse, error)
	ListPricingRulesByResource(ctx context.Context, in *ListPricingRulesByResourceRequest, opts ...grpc.CallOption) (*ListPricingRulesResponse, error)
	CreatePricingRule(ctx context.Context, in *CreatePricingRuleRequest, opts ...grpc.CallOption) (*CreatePricingRuleResponse, error)
	UpdatePricingRule(ctx context.Context, in *UpdatePricingRuleRequest, opts ...grpc.CallOption) (*UpdatePricingRuleResponse, error)
	DeletePricingRule(ctx context.Context, in *DeletePricingRuleRequest, opts ...grpc.CallOption) (*DeletePricingRuleResponse, error)
}

type merchantResourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantResourceServiceClient(cc grpc.ClientConnInterface) MerchantResourceServiceClient {
	return &merchantResourceServiceClient{cc}
}

func (c *merchantResourceServiceClient) CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResourceResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_CreateResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantResourceServiceClient) ListResourcesByFacility(ctx context.Context, in *ListResourcesByFacilityRequest, opts ...grpc.CallOption) (*ListResourcesByFacilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesByFacilityResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_ListResourcesByFacility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantResourceServiceClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantResourceServiceClient) UpdateResource(ctx context.Context, in *UpdateResourceRequest, opts ...grpc.CallOption) (*UpdateResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResourceResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_UpdateResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantResourceServiceClient) UpdateChildResource(ctx context.Context, in *UpdateChildResourceRequest, opts ...grpc.CallOption) (*UpdateChildResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateChildResourceResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_UpdateChildResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantResourceServiceClient) ListPricingRulesByResource(ctx context.Context, in *ListPricingRulesByResourceRequest, opts ...grpc.CallOption) (*ListPricingRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPricingRulesResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_ListPricingRulesByResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantResourceServiceClient) CreatePricingRule(ctx context.Context, in *CreatePricingRuleRequest, opts ...grpc.CallOption) (*CreatePricingRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePricingRuleResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_CreatePricingRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantResourceServiceClient) UpdatePricingRule(ctx context.Context, in *UpdatePricingRuleRequest, opts ...grpc.CallOption) (*UpdatePricingRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePricingRuleResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_UpdatePricingRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantResourceServiceClient) DeletePricingRule(ctx context.Context, in *DeletePricingRuleRequest, opts ...grpc.CallOption) (*DeletePricingRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePricingRuleResponse)
	err := c.cc.Invoke(ctx, MerchantResourceService_DeletePricingRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantResourceServiceServer is the server API for MerchantResourceService service.
// All implementations should embed UnimplementedMerchantResourceServiceServer
// for forward compatibility.
type MerchantResourceServiceServer interface {
	// API Tạo Sân con nằm trong Cơ sở
	CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error)
	// Danh sách resource theo facility (facility_id trong path để tránh trùng với resource_id).
	ListResourcesByFacility(context.Context, *ListResourcesByFacilityRequest) (*ListResourcesByFacilityResponse, error)
	GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error)
	UpdateResource(context.Context, *UpdateResourceRequest) (*UpdateResourceResponse, error)
	UpdateChildResource(context.Context, *UpdateChildResourceRequest) (*UpdateChildResourceResponse, error)
	ListPricingRulesByResource(context.Context, *ListPricingRulesByResourceRequest) (*ListPricingRulesResponse, error)
	CreatePricingRule(context.Context, *CreatePricingRuleRequest) (*CreatePricingRuleResponse, error)
	UpdatePricingRule(context.Context, *UpdatePricingRuleRequest) (*UpdatePricingRuleResponse, error)
	DeletePricingRule(context.Context, *DeletePricingRuleRequest) (*DeletePricingRuleResponse, error)
}

// UnimplementedMerchantResourceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantResourceServiceServer struct{}

func (UnimplementedMerchantResourceServiceServer) CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateResource not implemented")
}
func (UnimplementedMerchantResourceServiceServer) ListResourcesByFacility(context.Context, *ListResourcesByFacilityRequest) (*ListResourcesByFacilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResourcesByFacility not implemented")
}
func (UnimplementedMerchantResourceServiceServer) GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedMerchantResourceServiceServer) UpdateResource(context.Context, *UpdateResourceRequest) (*UpdateResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateResource not implemented")
}
func (UnimplementedMerchantResourceServiceServer) UpdateChildResource(context.Context, *UpdateChildResourceRequest) (*UpdateChildResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChildResource not implemented")
}
func (UnimplementedMerchantResourceServiceServer) ListPricingRulesByResource(context.Context, *ListPricingRulesByResourceRequest) (*ListPricingRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPricingRulesByResource not implemented")
}
func (UnimplementedMerchantResourceServiceServer) CreatePricingRule(context.Context, *CreatePricingRuleRequest) (*CreatePricingRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePricingRule not implemented")
}
func (UnimplementedMerchantResourceServiceServer) UpdatePricingRule(context.Context, *UpdatePricingRuleRequest) (*UpdatePricingRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePricingRule not implemented")
}
func (UnimplementedMerchantResourceServiceServer) DeletePricingRule(context.Context, *DeletePricingRuleRequest) (*DeletePricingRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePricingRule not implemented")
}
func (UnimplementedMerchantResourceServiceServer) testEmbeddedByValue() {}

// UnsafeMerchantResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantResourceServiceServer will
// result in compilation errors.
type UnsafeMerchantResourceServiceServer interface {
	mustEmbedUnimplementedMerchantResourceServiceServer()
}

func RegisterMerchantResourceServiceServer(s grpc.ServiceRegistrar, srv MerchantResourceServiceServer) {
	// If the following call panics, it indicates UnimplementedMerchantResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantResourceService_ServiceDesc, srv)
}

func _MerchantResourceService_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_CreateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).CreateResource(ctx, req.(*CreateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantResourceService_ListResourcesByFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesByFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).ListResourcesByFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_ListResourcesByFacility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).ListResourcesByFacility(ctx, req.(*ListResourcesByFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantResourceService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).GetResource(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantResourceService_UpdateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).UpdateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_UpdateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).UpdateResource(ctx, req.(*UpdateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantResourceService_UpdateChildResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChildResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).UpdateChildResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_UpdateChildResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).UpdateChildResource(ctx, req.(*UpdateChildResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantResourceService_ListPricingRulesByResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPricingRulesByResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).ListPricingRulesByResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_ListPricingRulesByResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).ListPricingRulesByResource(ctx, req.(*ListPricingRulesByResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantResourceService_CreatePricingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePricingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).CreatePricingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_CreatePricingRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).CreatePricingRule(ctx, req.(*CreatePricingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantResourceService_UpdatePricingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePricingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).UpdatePricingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_UpdatePricingRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).UpdatePricingRule(ctx, req.(*UpdatePricingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantResourceService_DeletePricingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePricingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantResourceServiceServer).DeletePricingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantResourceService_DeletePricingRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantResourceServiceServer).DeletePricingRule(ctx, req.(*DeletePricingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantResourceService_ServiceDesc is the grpc.ServiceDesc for MerchantResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.MerchantResourceService",
	HandlerType: (*MerchantResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResource",
			Handler:    _MerchantResourceService_CreateResource_Handler,
		},
		{
			MethodName: "ListResourcesByFacility",
			Handler:    _MerchantResourceService_ListResourcesByFacility_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _MerchantResourceService_GetResource_Handler,
		},
		{
			MethodName: "UpdateResource",
			Handler:    _MerchantResourceService_UpdateResource_Handler,
		},
		{
			MethodName: "UpdateChildResource",
			Handler:    _MerchantResourceService_UpdateChildResource_Handler,
		},
		{
			MethodName: "ListPricingRulesByResource",
			Handler:    _MerchantResourceService_ListPricingRulesByResource_Handler,
		},
		{
			MethodName: "CreatePricingRule",
			Handler:    _MerchantResourceService_CreatePricingRule_Handler,
		},
		{
			MethodName: "UpdatePricingRule",
			Handler:    _MerchantResourceService_UpdatePricingRule_Handler,
		},
		{
			MethodName: "DeletePricingRule",
			Handler:    _MerchantResourceService_DeletePricingRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog/v1/merchant_service.proto",
}
