// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/v1/pricing_messages.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Khung giờ (chuỗi "HH:MM" hoặc "HH:MM:SS"), timezone do client/facility quy ước sau
type PricingTimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *string                `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *string                `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingTimeRange) Reset() {
	*x = PricingTimeRange{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingTimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingTimeRange) ProtoMessage() {}

func (x *PricingTimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingTimeRange.ProtoReflect.Descriptor instead.
func (*PricingTimeRange) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PricingTimeRange) GetStartTime() string {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return ""
}

func (x *PricingTimeRange) GetEndTime() string {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return ""
}

type PricingDateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *string                `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"` // ISO date YYYY-MM-DD
	EndDate       *string                `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingDateRange) Reset() {
	*x = PricingDateRange{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingDateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingDateRange) ProtoMessage() {}

func (x *PricingDateRange) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingDateRange.ProtoReflect.Descriptor instead.
func (*PricingDateRange) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PricingDateRange) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *PricingDateRange) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

// Điều kiện áp dụng rule (lưu JSONB trong DB; API camelCase)
type PricingRuleConditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *PricingTimeRange      `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3,oneof" json:"time_range,omitempty"`
	DaysOfWeek    []int32                `protobuf:"varint,2,rep,packed,name=days_of_week,json=daysOfWeek,proto3" json:"days_of_week,omitempty"` // 1 = Thứ 2 … 7 = Chủ nhật (ISO weekday-style)
	DateRange     *PricingDateRange      `protobuf:"bytes,3,opt,name=date_range,json=dateRange,proto3,oneof" json:"date_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingRuleConditions) Reset() {
	*x = PricingRuleConditions{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingRuleConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRuleConditions) ProtoMessage() {}

func (x *PricingRuleConditions) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRuleConditions.ProtoReflect.Descriptor instead.
func (*PricingRuleConditions) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PricingRuleConditions) GetTimeRange() *PricingTimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *PricingRuleConditions) GetDaysOfWeek() []int32 {
	if x != nil {
		return x.DaysOfWeek
	}
	return nil
}

func (x *PricingRuleConditions) GetDateRange() *PricingDateRange {
	if x != nil {
		return x.DateRange
	}
	return nil
}

// Trả về cho Portal — display_label do backend sinh
type PriceAdjustmentView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // OVERRIDE | PERCENTAGE | FIXED
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	DisplayLabel  string                 `protobuf:"bytes,3,opt,name=display_label,json=displayLabel,proto3" json:"display_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceAdjustmentView) Reset() {
	*x = PriceAdjustmentView{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceAdjustmentView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceAdjustmentView) ProtoMessage() {}

func (x *PriceAdjustmentView) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceAdjustmentView.ProtoReflect.Descriptor instead.
func (*PriceAdjustmentView) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PriceAdjustmentView) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PriceAdjustmentView) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PriceAdjustmentView) GetDisplayLabel() string {
	if x != nil {
		return x.DisplayLabel
	}
	return ""
}

type MerchantPricingRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Adjustment    *PriceAdjustmentView   `protobuf:"bytes,4,opt,name=adjustment,proto3" json:"adjustment,omitempty"`
	Conditions    *PricingRuleConditions `protobuf:"bytes,5,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantPricingRule) Reset() {
	*x = MerchantPricingRule{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantPricingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantPricingRule) ProtoMessage() {}

func (x *MerchantPricingRule) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantPricingRule.ProtoReflect.Descriptor instead.
func (*MerchantPricingRule) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MerchantPricingRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantPricingRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantPricingRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MerchantPricingRule) GetAdjustment() *PriceAdjustmentView {
	if x != nil {
		return x.Adjustment
	}
	return nil
}

func (x *MerchantPricingRule) GetConditions() *PricingRuleConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *MerchantPricingRule) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantPricingRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PricingRuleResourceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,3,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingRuleResourceSummary) Reset() {
	*x = PricingRuleResourceSummary{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingRuleResourceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRuleResourceSummary) ProtoMessage() {}

func (x *PricingRuleResourceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRuleResourceSummary.ProtoReflect.Descriptor instead.
func (*PricingRuleResourceSummary) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PricingRuleResourceSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PricingRuleResourceSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PricingRuleResourceSummary) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

type ListPricingRulesByResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPricingRulesByResourceRequest) Reset() {
	*x = ListPricingRulesByResourceRequest{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPricingRulesByResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPricingRulesByResourceRequest) ProtoMessage() {}

func (x *ListPricingRulesByResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPricingRulesByResourceRequest.ProtoReflect.Descriptor instead.
func (*ListPricingRulesByResourceRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ListPricingRulesByResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ListPricingRulesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Resource      *PricingRuleResourceSummary `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	PricingRules  []*MerchantPricingRule      `protobuf:"bytes,2,rep,name=pricing_rules,json=pricingRules,proto3" json:"pricing_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPricingRulesResponse) Reset() {
	*x = ListPricingRulesResponse{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPricingRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPricingRulesResponse) ProtoMessage() {}

func (x *ListPricingRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPricingRulesResponse.ProtoReflect.Descriptor instead.
func (*ListPricingRulesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ListPricingRulesResponse) GetResource() *PricingRuleResourceSummary {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ListPricingRulesResponse) GetPricingRules() []*MerchantPricingRule {
	if x != nil {
		return x.PricingRules
	}
	return nil
}

type CreatePricingRuleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResourceId      string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Priority        int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	AdjustmentType  string                 `protobuf:"bytes,4,opt,name=adjustment_type,json=adjustmentType,proto3" json:"adjustment_type,omitempty"`
	AdjustmentValue float64                `protobuf:"fixed64,5,opt,name=adjustment_value,json=adjustmentValue,proto3" json:"adjustment_value,omitempty"`
	Conditions      *PricingRuleConditions `protobuf:"bytes,6,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Status          *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePricingRuleRequest) Reset() {
	*x = CreatePricingRuleRequest{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePricingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePricingRuleRequest) ProtoMessage() {}

func (x *CreatePricingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePricingRuleRequest.ProtoReflect.Descriptor instead.
func (*CreatePricingRuleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePricingRuleRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreatePricingRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePricingRuleRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreatePricingRuleRequest) GetAdjustmentType() string {
	if x != nil {
		return x.AdjustmentType
	}
	return ""
}

func (x *CreatePricingRuleRequest) GetAdjustmentValue() float64 {
	if x != nil {
		return x.AdjustmentValue
	}
	return 0
}

func (x *CreatePricingRuleRequest) GetConditions() *PricingRuleConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *CreatePricingRuleRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type CreatePricingRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PricingRule   *MerchantPricingRule   `protobuf:"bytes,1,opt,name=pricing_rule,json=pricingRule,proto3" json:"pricing_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePricingRuleResponse) Reset() {
	*x = CreatePricingRuleResponse{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePricingRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePricingRuleResponse) ProtoMessage() {}

func (x *CreatePricingRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePricingRuleResponse.ProtoReflect.Descriptor instead.
func (*CreatePricingRuleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePricingRuleResponse) GetPricingRule() *MerchantPricingRule {
	if x != nil {
		return x.PricingRule
	}
	return nil
}

type UpdatePricingRuleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PricingRuleId   string                 `protobuf:"bytes,1,opt,name=pricing_rule_id,json=pricingRuleId,proto3" json:"pricing_rule_id,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Priority        *int32                 `protobuf:"varint,3,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	AdjustmentType  *string                `protobuf:"bytes,4,opt,name=adjustment_type,json=adjustmentType,proto3,oneof" json:"adjustment_type,omitempty"`
	AdjustmentValue *float64               `protobuf:"fixed64,5,opt,name=adjustment_value,json=adjustmentValue,proto3,oneof" json:"adjustment_value,omitempty"`
	Conditions      *PricingRuleConditions `protobuf:"bytes,6,opt,name=conditions,proto3,oneof" json:"conditions,omitempty"`
	Status          *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePricingRuleRequest) Reset() {
	*x = UpdatePricingRuleRequest{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePricingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePricingRuleRequest) ProtoMessage() {}

func (x *UpdatePricingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePricingRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdatePricingRuleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePricingRuleRequest) GetPricingRuleId() string {
	if x != nil {
		return x.PricingRuleId
	}
	return ""
}

func (x *UpdatePricingRuleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePricingRuleRequest) GetPriority() int32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *UpdatePricingRuleRequest) GetAdjustmentType() string {
	if x != nil && x.AdjustmentType != nil {
		return *x.AdjustmentType
	}
	return ""
}

func (x *UpdatePricingRuleRequest) GetAdjustmentValue() float64 {
	if x != nil && x.AdjustmentValue != nil {
		return *x.AdjustmentValue
	}
	return 0
}

func (x *UpdatePricingRuleRequest) GetConditions() *PricingRuleConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *UpdatePricingRuleRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type UpdatePricingRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PricingRule   *MerchantPricingRule   `protobuf:"bytes,1,opt,name=pricing_rule,json=pricingRule,proto3" json:"pricing_rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePricingRuleResponse) Reset() {
	*x = UpdatePricingRuleResponse{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePricingRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePricingRuleResponse) ProtoMessage() {}

func (x *UpdatePricingRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePricingRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdatePricingRuleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePricingRuleResponse) GetPricingRule() *MerchantPricingRule {
	if x != nil {
		return x.PricingRule
	}
	return nil
}

type DeletePricingRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PricingRuleId string                 `protobuf:"bytes,1,opt,name=pricing_rule_id,json=pricingRuleId,proto3" json:"pricing_rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePricingRuleRequest) Reset() {
	*x = DeletePricingRuleRequest{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePricingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePricingRuleRequest) ProtoMessage() {}

func (x *DeletePricingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePricingRuleRequest.ProtoReflect.Descriptor instead.
func (*DeletePricingRuleRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePricingRuleRequest) GetPricingRuleId() string {
	if x != nil {
		return x.PricingRuleId
	}
	return ""
}

type DeletePricingRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePricingRuleResponse) Reset() {
	*x = DeletePricingRuleResponse{}
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePricingRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePricingRuleResponse) ProtoMessage() {}

func (x *DeletePricingRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_pricing_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePricingRuleResponse.ProtoReflect.Descriptor instead.
func (*DeletePricingRuleResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_pricing_messages_proto_rawDescGZIP(), []int{13}
}

var File_catalog_v1_pricing_messages_proto protoreflect.FileDescriptor

const file_catalog_v1_pricing_messages_proto_rawDesc = "" +
	"\n" +
	"!catalog/v1/pricing_messages.proto\x12\n" +
	"catalog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"r\n" +
	"\x10PricingTimeRange\x12\"\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tH\x00R\tstartTime\x88\x01\x01\x12\x1e\n" +
	"\bend_time\x18\x02 \x01(\tH\x01R\aendTime\x88\x01\x01B\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"r\n" +
	"\x10PricingDateRange\x12\"\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tH\x00R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x02 \x01(\tH\x01R\aendDate\x88\x01\x01B\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_date\"\xdb\x01\n" +
	"\x15PricingRuleConditions\x12@\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2\x1c.catalog.v1.PricingTimeRangeH\x00R\ttimeRange\x88\x01\x01\x12 \n" +
	"\fdays_of_week\x18\x02 \x03(\x05R\n" +
	"daysOfWeek\x12@\n" +
	"\n" +
	"date_range\x18\x03 \x01(\v2\x1c.catalog.v1.PricingDateRangeH\x01R\tdateRange\x88\x01\x01B\r\n" +
	"\v_time_rangeB\r\n" +
	"\v_date_range\"d\n" +
	"\x13PriceAdjustmentView\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12#\n" +
	"\rdisplay_label\x18\x03 \x01(\tR\fdisplayLabel\"\xac\x02\n" +
	"\x13MerchantPricingRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12?\n" +
	"\n" +
	"adjustment\x18\x04 \x01(\v2\x1f.catalog.v1.PriceAdjustmentViewR\n" +
	"adjustment\x12A\n" +
	"\n" +
	"conditions\x18\x05 \x01(\v2!.catalog.v1.PricingRuleConditionsR\n" +
	"conditions\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"_\n" +
	"\x1aPricingRuleResourceSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"base_price\x18\x03 \x01(\x01R\tbasePrice\"D\n" +
	"!ListPricingRulesByResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"\xa4\x01\n" +
	"\x18ListPricingRulesResponse\x12B\n" +
	"\bresource\x18\x01 \x01(\v2&.catalog.v1.PricingRuleResourceSummaryR\bresource\x12D\n" +
	"\rpricing_rules\x18\x02 \x03(\v2\x1f.catalog.v1.MerchantPricingRuleR\fpricingRules\"\xaa\x02\n" +
	"\x18CreatePricingRuleRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12'\n" +
	"\x0fadjustment_type\x18\x04 \x01(\tR\x0eadjustmentType\x12)\n" +
	"\x10adjustment_value\x18\x05 \x01(\x01R\x0fadjustmentValue\x12A\n" +
	"\n" +
	"conditions\x18\x06 \x01(\v2!.catalog.v1.PricingRuleConditionsR\n" +
	"conditions\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"_\n" +
	"\x19CreatePricingRuleResponse\x12B\n" +
	"\fpricing_rule\x18\x01 \x01(\v2\x1f.catalog.v1.MerchantPricingRuleR\vpricingRule\"\x98\x03\n" +
	"\x18UpdatePricingRuleRequest\x12&\n" +
	"\x0fpricing_rule_id\x18\x01 \x01(\tR\rpricingRuleId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x03 \x01(\x05H\x01R\bpriority\x88\x01\x01\x12,\n" +
	"\x0fadjustment_type\x18\x04 \x01(\tH\x02R\x0eadjustmentType\x88\x01\x01\x12.\n" +
	"\x10adjustment_value\x18\x05 \x01(\x01H\x03R\x0fadjustmentValue\x88\x01\x01\x12F\n" +
	"\n" +
	"conditions\x18\x06 \x01(\v2!.catalog.v1.PricingRuleConditionsH\x04R\n" +
	"conditions\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x05R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_priorityB\x12\n" +
	"\x10_adjustment_typeB\x13\n" +
	"\x11_adjustment_valueB\r\n" +
	"\v_conditionsB\t\n" +
	"\a_status\"_\n" +
	"\x19UpdatePricingRuleResponse\x12B\n" +
	"\fpricing_rule\x18\x01 \x01(\v2\x1f.catalog.v1.MerchantPricingRuleR\vpricingRule\"B\n" +
	"\x18DeletePricingRuleRequest\x12&\n" +
	"\x0fpricing_rule_id\x18\x01 \x01(\tR\rpricingRuleId\"\x1b\n" +
	"\x19DeletePricingRuleResponseBEZCgithub.com/khoitran2003/sportinas-be-proto-gen/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_pricing_messages_proto_rawDescOnce sync.Once
	file_catalog_v1_pricing_messages_proto_rawDescData []byte
)

func file_catalog_v1_pricing_messages_proto_rawDescGZIP() []byte {
	file_catalog_v1_pricing_messages_proto_rawDescOnce.Do(func() {
		file_catalog_v1_pricing_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_pricing_messages_proto_rawDesc), len(file_catalog_v1_pricing_messages_proto_rawDesc)))
	})
	return file_catalog_v1_pricing_messages_proto_rawDescData
}

var file_catalog_v1_pricing_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_catalog_v1_pricing_messages_proto_goTypes = []any{
	(*PricingTimeRange)(nil),                  // 0: catalog.v1.PricingTimeRange
	(*PricingDateRange)(nil),                  // 1: catalog.v1.PricingDateRange
	(*PricingRuleConditions)(nil),             // 2: catalog.v1.PricingRuleConditions
	(*PriceAdjustmentView)(nil),               // 3: catalog.v1.PriceAdjustmentView
	(*MerchantPricingRule)(nil),               // 4: catalog.v1.MerchantPricingRule
	(*PricingRuleResourceSummary)(nil),        // 5: catalog.v1.PricingRuleResourceSummary
	(*ListPricingRulesByResourceRequest)(nil), // 6: catalog.v1.ListPricingRulesByResourceRequest
	(*ListPricingRulesResponse)(nil),          // 7: catalog.v1.ListPricingRulesResponse
	(*CreatePricingRuleRequest)(nil),          // 8: catalog.v1.CreatePricingRuleRequest
	(*CreatePricingRuleResponse)(nil),         // 9: catalog.v1.CreatePricingRuleResponse
	(*UpdatePricingRuleRequest)(nil),          // 10: catalog.v1.UpdatePricingRuleRequest
	(*UpdatePricingRuleResponse)(nil),         // 11: catalog.v1.UpdatePricingRuleResponse
	(*DeletePricingRuleRequest)(nil),          // 12: catalog.v1.DeletePricingRuleRequest
	(*DeletePricingRuleResponse)(nil),         // 13: catalog.v1.DeletePricingRuleResponse
	(*timestamppb.Timestamp)(nil),             // 14: google.protobuf.Timestamp
}
var file_catalog_v1_pricing_messages_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.PricingRuleConditions.time_range:type_name -> catalog.v1.PricingTimeRange
	1,  // 1: catalog.v1.PricingRuleConditions.date_range:type_name -> catalog.v1.PricingDateRange
	3,  // 2: catalog.v1.MerchantPricingRule.adjustment:type_name -> catalog.v1.PriceAdjustmentView
	2,  // 3: catalog.v1.MerchantPricingRule.conditions:type_name -> catalog.v1.PricingRuleConditions
	14, // 4: catalog.v1.MerchantPricingRule.created_at:type_name -> google.protobuf.Timestamp
	5,  // 5: catalog.v1.ListPricingRulesResponse.resource:type_name -> catalog.v1.PricingRuleResourceSummary
	4,  // 6: catalog.v1.ListPricingRulesResponse.pricing_rules:type_name -> catalog.v1.MerchantPricingRule
	2,  // 7: catalog.v1.CreatePricingRuleRequest.conditions:type_name -> catalog.v1.PricingRuleConditions
	4,  // 8: catalog.v1.CreatePricingRuleResponse.pricing_rule:type_name -> catalog.v1.MerchantPricingRule
	2,  // 9: catalog.v1.UpdatePricingRuleRequest.conditions:type_name -> catalog.v1.PricingRuleConditions
	4,  // 10: catalog.v1.UpdatePricingRuleResponse.pricing_rule:type_name -> catalog.v1.MerchantPricingRule
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_catalog_v1_pricing_messages_proto_init() }
func file_catalog_v1_pricing_messages_proto_init() {
	if File_catalog_v1_pricing_messages_proto != nil {
		return
	}
	file_catalog_v1_pricing_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_catalog_v1_pricing_messages_proto_msgTypes[1].OneofWrappers = []any{}
	file_catalog_v1_pricing_messages_proto_msgTypes[2].OneofWrappers = []any{}
	file_catalog_v1_pricing_messages_proto_msgTypes[8].OneofWrappers = []any{}
	file_catalog_v1_pricing_messages_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_pricing_messages_proto_rawDesc), len(file_catalog_v1_pricing_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_v1_pricing_messages_proto_goTypes,
		DependencyIndexes: file_catalog_v1_pricing_messages_proto_depIdxs,
		MessageInfos:      file_catalog_v1_pricing_messages_proto_msgTypes,
	}.Build()
	File_catalog_v1_pricing_messages_proto = out.File
	file_catalog_v1_pricing_messages_proto_goTypes = nil
	file_catalog_v1_pricing_messages_proto_depIdxs = nil
}
