// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/v1/public_service.proto

package catalogv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_catalog_v1_public_service_proto protoreflect.FileDescriptor

const file_catalog_v1_public_service_proto_rawDesc = "" +
	"\n" +
	"\x1fcatalog/v1/public_service.proto\x12\n" +
	"catalog.v1\x1a!catalog/v1/catalog_messages.proto\x1a\"catalog/v1/facility_messages.proto\x1a\"catalog/v1/resource_messages.proto\x1a\x1cgoogle/api/annotations.proto2\x98\x06\n" +
	"\x15PublicFacilityService\x12\x8c\x01\n" +
	"\x14ListPublicFacilities\x12'.catalog.v1.ListPublicFacilitiesRequest\x1a(.catalog.v1.ListPublicFacilitiesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/public/facilities\x12\x98\x01\n" +
	"\x16SearchPublicFacilities\x12'.catalog.v1.ListPublicFacilitiesRequest\x1a(.catalog.v1.ListPublicFacilitiesResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/public/facilities:search\x12\x9a\x01\n" +
	"\x17GetDetailPublicFacility\x12*.catalog.v1.GetDetailPublicFacilityRequest\x1a+.catalog.v1.GetDetailPublicFacilityResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/public/facilities/{id}\x12\xa1\x01\n" +
	"\x13ListPublicResources\x12&.catalog.v1.ListPublicResourcesRequest\x1a'.catalog.v1.ListPublicResourcesResponse\"9\x82\xd3\xe4\x93\x023\x121/api/v1/public/facilities/{facility_id}/resources\x12\x93\x01\n" +
	"\x10GetResourceSlots\x12#.catalog.v1.GetResourceSlotsRequest\x1a$.catalog.v1.GetResourceSlotsResponse\"4\x82\xd3\xe4\x93\x02.\x12,/api/v1/public/resources/{resource_id}/slots2\x85\a\n" +
	"\x14PublicCatalogService\x12\x8f\x01\n" +
	"\x13ListSportCategories\x12&.catalog.v1.ListSportCategoriesRequest\x1a'.catalog.v1.ListSportCategoriesResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/public/sport-categories\x12\x80\x01\n" +
	"\x10GetSportCategory\x12#.catalog.v1.GetSportCategoryRequest\x1a\x19.catalog.v1.SportCategory\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/public/sport-categories/{id}\x12j\n" +
	"\n" +
	"ListSports\x12\x1d.catalog.v1.ListSportsRequest\x1a\x1e.catalog.v1.ListSportsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/public/sports\x12\x93\x01\n" +
	"\x0eGetSportSchema\x12!.catalog.v1.GetSportSchemaRequest\x1a\".catalog.v1.GetSportSchemaResponse\":\x82\xd3\xe4\x93\x024\x122/api/v1/public/metadata/sports/{sport_code}/schema\x12v\n" +
	"\rListProvinces\x12 .catalog.v1.ListProvincesRequest\x1a!.catalog.v1.ListProvincesResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/public/provinces\x12v\n" +
	"\rListDistricts\x12 .catalog.v1.ListDistrictsRequest\x1a!.catalog.v1.ListDistrictsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/public/districts\x12f\n" +
	"\tListWards\x12\x1c.catalog.v1.ListWardsRequest\x1a\x1d.catalog.v1.ListWardsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/public/wardsBEZCgithub.com/khoitran2003/sportinas-be-proto-gen/catalog/v1;catalogv1b\x06proto3"

var file_catalog_v1_public_service_proto_goTypes = []any{
	(*ListPublicFacilitiesRequest)(nil),     // 0: catalog.v1.ListPublicFacilitiesRequest
	(*GetDetailPublicFacilityRequest)(nil),  // 1: catalog.v1.GetDetailPublicFacilityRequest
	(*ListPublicResourcesRequest)(nil),      // 2: catalog.v1.ListPublicResourcesRequest
	(*GetResourceSlotsRequest)(nil),         // 3: catalog.v1.GetResourceSlotsRequest
	(*ListSportCategoriesRequest)(nil),      // 4: catalog.v1.ListSportCategoriesRequest
	(*GetSportCategoryRequest)(nil),         // 5: catalog.v1.GetSportCategoryRequest
	(*ListSportsRequest)(nil),               // 6: catalog.v1.ListSportsRequest
	(*GetSportSchemaRequest)(nil),           // 7: catalog.v1.GetSportSchemaRequest
	(*ListProvincesRequest)(nil),            // 8: catalog.v1.ListProvincesRequest
	(*ListDistrictsRequest)(nil),            // 9: catalog.v1.ListDistrictsRequest
	(*ListWardsRequest)(nil),                // 10: catalog.v1.ListWardsRequest
	(*ListPublicFacilitiesResponse)(nil),    // 11: catalog.v1.ListPublicFacilitiesResponse
	(*GetDetailPublicFacilityResponse)(nil), // 12: catalog.v1.GetDetailPublicFacilityResponse
	(*ListPublicResourcesResponse)(nil),     // 13: catalog.v1.ListPublicResourcesResponse
	(*GetResourceSlotsResponse)(nil),        // 14: catalog.v1.GetResourceSlotsResponse
	(*ListSportCategoriesResponse)(nil),     // 15: catalog.v1.ListSportCategoriesResponse
	(*SportCategory)(nil),                   // 16: catalog.v1.SportCategory
	(*ListSportsResponse)(nil),              // 17: catalog.v1.ListSportsResponse
	(*GetSportSchemaResponse)(nil),          // 18: catalog.v1.GetSportSchemaResponse
	(*ListProvincesResponse)(nil),           // 19: catalog.v1.ListProvincesResponse
	(*ListDistrictsResponse)(nil),           // 20: catalog.v1.ListDistrictsResponse
	(*ListWardsResponse)(nil),               // 21: catalog.v1.ListWardsResponse
}
var file_catalog_v1_public_service_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.PublicFacilityService.ListPublicFacilities:input_type -> catalog.v1.ListPublicFacilitiesRequest
	0,  // 1: catalog.v1.PublicFacilityService.SearchPublicFacilities:input_type -> catalog.v1.ListPublicFacilitiesRequest
	1,  // 2: catalog.v1.PublicFacilityService.GetDetailPublicFacility:input_type -> catalog.v1.GetDetailPublicFacilityRequest
	2,  // 3: catalog.v1.PublicFacilityService.ListPublicResources:input_type -> catalog.v1.ListPublicResourcesRequest
	3,  // 4: catalog.v1.PublicFacilityService.GetResourceSlots:input_type -> catalog.v1.GetResourceSlotsRequest
	4,  // 5: catalog.v1.PublicCatalogService.ListSportCategories:input_type -> catalog.v1.ListSportCategoriesRequest
	5,  // 6: catalog.v1.PublicCatalogService.GetSportCategory:input_type -> catalog.v1.GetSportCategoryRequest
	6,  // 7: catalog.v1.PublicCatalogService.ListSports:input_type -> catalog.v1.ListSportsRequest
	7,  // 8: catalog.v1.PublicCatalogService.GetSportSchema:input_type -> catalog.v1.GetSportSchemaRequest
	8,  // 9: catalog.v1.PublicCatalogService.ListProvinces:input_type -> catalog.v1.ListProvincesRequest
	9,  // 10: catalog.v1.PublicCatalogService.ListDistricts:input_type -> catalog.v1.ListDistrictsRequest
	10, // 11: catalog.v1.PublicCatalogService.ListWards:input_type -> catalog.v1.ListWardsRequest
	11, // 12: catalog.v1.PublicFacilityService.ListPublicFacilities:output_type -> catalog.v1.ListPublicFacilitiesResponse
	11, // 13: catalog.v1.PublicFacilityService.SearchPublicFacilities:output_type -> catalog.v1.ListPublicFacilitiesResponse
	12, // 14: catalog.v1.PublicFacilityService.GetDetailPublicFacility:output_type -> catalog.v1.GetDetailPublicFacilityResponse
	13, // 15: catalog.v1.PublicFacilityService.ListPublicResources:output_type -> catalog.v1.ListPublicResourcesResponse
	14, // 16: catalog.v1.PublicFacilityService.GetResourceSlots:output_type -> catalog.v1.GetResourceSlotsResponse
	15, // 17: catalog.v1.PublicCatalogService.ListSportCategories:output_type -> catalog.v1.ListSportCategoriesResponse
	16, // 18: catalog.v1.PublicCatalogService.GetSportCategory:output_type -> catalog.v1.SportCategory
	17, // 19: catalog.v1.PublicCatalogService.ListSports:output_type -> catalog.v1.ListSportsResponse
	18, // 20: catalog.v1.PublicCatalogService.GetSportSchema:output_type -> catalog.v1.GetSportSchemaResponse
	19, // 21: catalog.v1.PublicCatalogService.ListProvinces:output_type -> catalog.v1.ListProvincesResponse
	20, // 22: catalog.v1.PublicCatalogService.ListDistricts:output_type -> catalog.v1.ListDistrictsResponse
	21, // 23: catalog.v1.PublicCatalogService.ListWards:output_type -> catalog.v1.ListWardsResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_v1_public_service_proto_init() }
func file_catalog_v1_public_service_proto_init() {
	if File_catalog_v1_public_service_proto != nil {
		return
	}
	file_catalog_v1_catalog_messages_proto_init()
	file_catalog_v1_facility_messages_proto_init()
	file_catalog_v1_resource_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_public_service_proto_rawDesc), len(file_catalog_v1_public_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_catalog_v1_public_service_proto_goTypes,
		DependencyIndexes: file_catalog_v1_public_service_proto_depIdxs,
	}.Build()
	File_catalog_v1_public_service_proto = out.File
	file_catalog_v1_public_service_proto_goTypes = nil
	file_catalog_v1_public_service_proto_depIdxs = nil
}
