// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth_service.proto

package authv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_v1_auth_service_proto protoreflect.FileDescriptor

const file_auth_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1aauth/v1/auth_service.proto\x12\aauth.v1\x1a\x1bauth/v1/auth_messages.proto\x1a\x1cgoogle/api/annotations.proto2\xb9\x01\n" +
	"\vAuthService\x12U\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12S\n" +
	"\x0eDeleteIdentity\x12\x1e.auth.v1.DeleteIdentityRequest\x1a\x1f.auth.v1.DeleteIdentityResponse\"\x00B?Z=github.com/khoitran2003/sportinas-be-proto-gen/auth/v1;authv1b\x06proto3"

var file_auth_v1_auth_service_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: auth.v1.LoginRequest
	(*DeleteIdentityRequest)(nil),  // 1: auth.v1.DeleteIdentityRequest
	(*LoginResponse)(nil),          // 2: auth.v1.LoginResponse
	(*DeleteIdentityResponse)(nil), // 3: auth.v1.DeleteIdentityResponse
}
var file_auth_v1_auth_service_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	1, // 1: auth.v1.AuthService.DeleteIdentity:input_type -> auth.v1.DeleteIdentityRequest
	2, // 2: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	3, // 3: auth.v1.AuthService.DeleteIdentity:output_type -> auth.v1.DeleteIdentityResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_service_proto_init() }
func file_auth_v1_auth_service_proto_init() {
	if File_auth_v1_auth_service_proto != nil {
		return
	}
	file_auth_v1_auth_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_service_proto_rawDesc), len(file_auth_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_service_proto_depIdxs,
	}.Build()
	File_auth_v1_auth_service_proto = out.File
	file_auth_v1_auth_service_proto_goTypes = nil
	file_auth_v1_auth_service_proto_depIdxs = nil
}
