// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/internal_messages.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInternalAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInternalAuthRequest) Reset() {
	*x = CreateInternalAuthRequest{}
	mi := &file_auth_v1_internal_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInternalAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInternalAuthRequest) ProtoMessage() {}

func (x *CreateInternalAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_internal_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInternalAuthRequest.ProtoReflect.Descriptor instead.
func (*CreateInternalAuthRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_internal_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInternalAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateInternalAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateInternalAuthRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type CreateInternalAuthResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InternalAuthAdminId string                 `protobuf:"bytes,1,opt,name=internal_auth_admin_id,json=internalAuthAdminId,proto3" json:"internal_auth_admin_id,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateInternalAuthResponse) Reset() {
	*x = CreateInternalAuthResponse{}
	mi := &file_auth_v1_internal_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInternalAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInternalAuthResponse) ProtoMessage() {}

func (x *CreateInternalAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_internal_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInternalAuthResponse.ProtoReflect.Descriptor instead.
func (*CreateInternalAuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_internal_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInternalAuthResponse) GetInternalAuthAdminId() string {
	if x != nil {
		return x.InternalAuthAdminId
	}
	return ""
}

func (x *CreateInternalAuthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_auth_v1_internal_messages_proto protoreflect.FileDescriptor

const file_auth_v1_internal_messages_proto_rawDesc = "" +
	"\n" +
	"\x1fauth/v1/internal_messages.proto\x12\aauth.v1\"h\n" +
	"\x19CreateInternalAuthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"k\n" +
	"\x1aCreateInternalAuthResponse\x123\n" +
	"\x16internal_auth_admin_id\x18\x01 \x01(\tR\x13internalAuthAdminId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB?Z=github.com/khoitran2003/sportinas-be-proto-gen/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_internal_messages_proto_rawDescOnce sync.Once
	file_auth_v1_internal_messages_proto_rawDescData []byte
)

func file_auth_v1_internal_messages_proto_rawDescGZIP() []byte {
	file_auth_v1_internal_messages_proto_rawDescOnce.Do(func() {
		file_auth_v1_internal_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_internal_messages_proto_rawDesc), len(file_auth_v1_internal_messages_proto_rawDesc)))
	})
	return file_auth_v1_internal_messages_proto_rawDescData
}

var file_auth_v1_internal_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_v1_internal_messages_proto_goTypes = []any{
	(*CreateInternalAuthRequest)(nil),  // 0: auth.v1.CreateInternalAuthRequest
	(*CreateInternalAuthResponse)(nil), // 1: auth.v1.CreateInternalAuthResponse
}
var file_auth_v1_internal_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_internal_messages_proto_init() }
func file_auth_v1_internal_messages_proto_init() {
	if File_auth_v1_internal_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_internal_messages_proto_rawDesc), len(file_auth_v1_internal_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_internal_messages_proto_goTypes,
		DependencyIndexes: file_auth_v1_internal_messages_proto_depIdxs,
		MessageInfos:      file_auth_v1_internal_messages_proto_msgTypes,
	}.Build()
	File_auth_v1_internal_messages_proto = out.File
	file_auth_v1_internal_messages_proto_goTypes = nil
	file_auth_v1_internal_messages_proto_depIdxs = nil
}
