// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/internal_messages.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInternalAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	RoleName      string                 `protobuf:"bytes,6,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInternalAdminRequest) Reset() {
	*x = CreateInternalAdminRequest{}
	mi := &file_user_v1_internal_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInternalAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInternalAdminRequest) ProtoMessage() {}

func (x *CreateInternalAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_internal_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInternalAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateInternalAdminRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_internal_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInternalAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateInternalAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateInternalAdminRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateInternalAdminRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateInternalAdminRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateInternalAdminRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type CreateInternalAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInternalAdminResponse) Reset() {
	*x = CreateInternalAdminResponse{}
	mi := &file_user_v1_internal_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInternalAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInternalAdminResponse) ProtoMessage() {}

func (x *CreateInternalAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_internal_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInternalAdminResponse.ProtoReflect.Descriptor instead.
func (*CreateInternalAdminResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_internal_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInternalAdminResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInternalAdminResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateInternalAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_v1_internal_messages_proto protoreflect.FileDescriptor

const file_user_v1_internal_messages_proto_rawDesc = "" +
	"\n" +
	"\x1fuser/v1/internal_messages.proto\x12\auser.v1\"\xb6\x01\n" +
	"\x1aCreateInternalAdminRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x1b\n" +
	"\trole_name\x18\x06 \x01(\tR\broleName\"f\n" +
	"\x1bCreateInternalAdminResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB?Z=github.com/khoitran2003/sportinas-be-proto-gen/user/v1;userv1b\x06proto3"

var (
	file_user_v1_internal_messages_proto_rawDescOnce sync.Once
	file_user_v1_internal_messages_proto_rawDescData []byte
)

func file_user_v1_internal_messages_proto_rawDescGZIP() []byte {
	file_user_v1_internal_messages_proto_rawDescOnce.Do(func() {
		file_user_v1_internal_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_internal_messages_proto_rawDesc), len(file_user_v1_internal_messages_proto_rawDesc)))
	})
	return file_user_v1_internal_messages_proto_rawDescData
}

var file_user_v1_internal_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_internal_messages_proto_goTypes = []any{
	(*CreateInternalAdminRequest)(nil),  // 0: user.v1.CreateInternalAdminRequest
	(*CreateInternalAdminResponse)(nil), // 1: user.v1.CreateInternalAdminResponse
}
var file_user_v1_internal_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_internal_messages_proto_init() }
func file_user_v1_internal_messages_proto_init() {
	if File_user_v1_internal_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_internal_messages_proto_rawDesc), len(file_user_v1_internal_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_internal_messages_proto_goTypes,
		DependencyIndexes: file_user_v1_internal_messages_proto_depIdxs,
		MessageInfos:      file_user_v1_internal_messages_proto_msgTypes,
	}.Build()
	File_user_v1_internal_messages_proto = out.File
	file_user_v1_internal_messages_proto_goTypes = nil
	file_user_v1_internal_messages_proto_depIdxs = nil
}
