// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/merchant_service.proto

package userv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_v1_merchant_service_proto protoreflect.FileDescriptor

const file_user_v1_merchant_service_proto_rawDesc = "" +
	"\n" +
	"\x1euser/v1/merchant_service.proto\x12\auser.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fuser/v1/merchant_messages.proto2\x8e\x02\n" +
	"\x0fMerchantService\x12u\n" +
	"\x0eCreateMerchant\x12\x1e.user.v1.CreateMerchantRequest\x1a\x1f.user.v1.CreateMerchantResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/users/merchants\x12\x83\x01\n" +
	"\x0fGetMerchantByID\x12\x1f.user.v1.GetMerchantByIDRequest\x1a .user.v1.GetMerchantByIDResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/users/merchants/{merchant_id}B2Z0github.com/Sportinas/be-proto-gen/user/v1;userv1b\x06proto3"

var file_user_v1_merchant_service_proto_goTypes = []any{
	(*CreateMerchantRequest)(nil),   // 0: user.v1.CreateMerchantRequest
	(*GetMerchantByIDRequest)(nil),  // 1: user.v1.GetMerchantByIDRequest
	(*CreateMerchantResponse)(nil),  // 2: user.v1.CreateMerchantResponse
	(*GetMerchantByIDResponse)(nil), // 3: user.v1.GetMerchantByIDResponse
}
var file_user_v1_merchant_service_proto_depIdxs = []int32{
	0, // 0: user.v1.MerchantService.CreateMerchant:input_type -> user.v1.CreateMerchantRequest
	1, // 1: user.v1.MerchantService.GetMerchantByID:input_type -> user.v1.GetMerchantByIDRequest
	2, // 2: user.v1.MerchantService.CreateMerchant:output_type -> user.v1.CreateMerchantResponse
	3, // 3: user.v1.MerchantService.GetMerchantByID:output_type -> user.v1.GetMerchantByIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_merchant_service_proto_init() }
func file_user_v1_merchant_service_proto_init() {
	if File_user_v1_merchant_service_proto != nil {
		return
	}
	file_user_v1_merchant_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_merchant_service_proto_rawDesc), len(file_user_v1_merchant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_merchant_service_proto_goTypes,
		DependencyIndexes: file_user_v1_merchant_service_proto_depIdxs,
	}.Build()
	File_user_v1_merchant_service_proto = out.File
	file_user_v1_merchant_service_proto_goTypes = nil
	file_user_v1_merchant_service_proto_depIdxs = nil
}
