// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/merchant_messages.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantStatus int32

const (
	MerchantStatus_MERCHANT_STATUS_UNSPECIFIED MerchantStatus = 0
	MerchantStatus_MERCHANT_STATUS_ACTIVE      MerchantStatus = 1
	MerchantStatus_MERCHANT_STATUS_INACTIVE    MerchantStatus = 2
	MerchantStatus_MERCHANT_STATUS_SUSPENDED   MerchantStatus = 3
	MerchantStatus_MERCHANT_STATUS_PENDING     MerchantStatus = 4
)

// Enum value maps for MerchantStatus.
var (
	MerchantStatus_name = map[int32]string{
		0: "MERCHANT_STATUS_UNSPECIFIED",
		1: "MERCHANT_STATUS_ACTIVE",
		2: "MERCHANT_STATUS_INACTIVE",
		3: "MERCHANT_STATUS_SUSPENDED",
		4: "MERCHANT_STATUS_PENDING",
	}
	MerchantStatus_value = map[string]int32{
		"MERCHANT_STATUS_UNSPECIFIED": 0,
		"MERCHANT_STATUS_ACTIVE":      1,
		"MERCHANT_STATUS_INACTIVE":    2,
		"MERCHANT_STATUS_SUSPENDED":   3,
		"MERCHANT_STATUS_PENDING":     4,
	}
)

func (x MerchantStatus) Enum() *MerchantStatus {
	p := new(MerchantStatus)
	*p = x
	return p
}

func (x MerchantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MerchantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_merchant_messages_proto_enumTypes[0].Descriptor()
}

func (MerchantStatus) Type() protoreflect.EnumType {
	return &file_user_v1_merchant_messages_proto_enumTypes[0]
}

func (x MerchantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MerchantStatus.Descriptor instead.
func (MerchantStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_merchant_messages_proto_rawDescGZIP(), []int{0}
}

type CreateMerchantRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain          string                 `protobuf:"bytes,2,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Email              string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PlatformFeePercent int32                  `protobuf:"varint,4,opt,name=platform_fee_percent,json=platformFeePercent,proto3" json:"platform_fee_percent,omitempty"`
	OwnerFullName      string                 `protobuf:"bytes,5,opt,name=owner_full_name,json=ownerFullName,proto3" json:"owner_full_name,omitempty"`
	OwnerPhone         string                 `protobuf:"bytes,6,opt,name=owner_phone,json=ownerPhone,proto3" json:"owner_phone,omitempty"`
	OwnerPassword      string                 `protobuf:"bytes,7,opt,name=owner_password,json=ownerPassword,proto3" json:"owner_password,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateMerchantRequest) Reset() {
	*x = CreateMerchantRequest{}
	mi := &file_user_v1_merchant_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantRequest) ProtoMessage() {}

func (x *CreateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_merchant_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_merchant_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMerchantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMerchantRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *CreateMerchantRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateMerchantRequest) GetPlatformFeePercent() int32 {
	if x != nil {
		return x.PlatformFeePercent
	}
	return 0
}

func (x *CreateMerchantRequest) GetOwnerFullName() string {
	if x != nil {
		return x.OwnerFullName
	}
	return ""
}

func (x *CreateMerchantRequest) GetOwnerPhone() string {
	if x != nil {
		return x.OwnerPhone
	}
	return ""
}

func (x *CreateMerchantRequest) GetOwnerPassword() string {
	if x != nil {
		return x.OwnerPassword
	}
	return ""
}

type CreateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Subdomain     string                 `protobuf:"bytes,2,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	SchemaName    string                 `protobuf:"bytes,3,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,4,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Status        MerchantStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=user.v1.MerchantStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantResponse) Reset() {
	*x = CreateMerchantResponse{}
	mi := &file_user_v1_merchant_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantResponse) ProtoMessage() {}

func (x *CreateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_merchant_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantResponse.ProtoReflect.Descriptor instead.
func (*CreateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_merchant_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMerchantResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateMerchantResponse) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *CreateMerchantResponse) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *CreateMerchantResponse) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *CreateMerchantResponse) GetStatus() MerchantStatus {
	if x != nil {
		return x.Status
	}
	return MerchantStatus_MERCHANT_STATUS_UNSPECIFIED
}

func (x *CreateMerchantResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetMerchantByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantByIDRequest) Reset() {
	*x = GetMerchantByIDRequest{}
	mi := &file_user_v1_merchant_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantByIDRequest) ProtoMessage() {}

func (x *GetMerchantByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_merchant_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantByIDRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_merchant_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantByIDRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantInfo          `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantByIDResponse) Reset() {
	*x = GetMerchantByIDResponse{}
	mi := &file_user_v1_merchant_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantByIDResponse) ProtoMessage() {}

func (x *GetMerchantByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_merchant_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantByIDResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantByIDResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_merchant_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantByIDResponse) GetMerchant() *MerchantInfo {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type MerchantInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MerchantId         string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain          string                 `protobuf:"bytes,3,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Email              string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	SchemaName         string                 `protobuf:"bytes,5,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	PlatformFeePercent int32                  `protobuf:"varint,6,opt,name=platform_fee_percent,json=platformFeePercent,proto3" json:"platform_fee_percent,omitempty"`
	Status             MerchantStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=user.v1.MerchantStatus" json:"status,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MerchantInfo) Reset() {
	*x = MerchantInfo{}
	mi := &file_user_v1_merchant_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantInfo) ProtoMessage() {}

func (x *MerchantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_merchant_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantInfo.ProtoReflect.Descriptor instead.
func (*MerchantInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_merchant_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MerchantInfo) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantInfo) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *MerchantInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MerchantInfo) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *MerchantInfo) GetPlatformFeePercent() int32 {
	if x != nil {
		return x.PlatformFeePercent
	}
	return 0
}

func (x *MerchantInfo) GetStatus() MerchantStatus {
	if x != nil {
		return x.Status
	}
	return MerchantStatus_MERCHANT_STATUS_UNSPECIFIED
}

func (x *MerchantInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetMerchantByKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantByKeyRequest) Reset() {
	*x = GetMerchantByKeyRequest{}
	mi := &file_user_v1_merchant_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantByKeyRequest) ProtoMessage() {}

func (x *GetMerchantByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_merchant_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantByKeyRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantByKeyRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_merchant_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetMerchantByKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetMerchantByKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *MerchantInfo          `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantByKeyResponse) Reset() {
	*x = GetMerchantByKeyResponse{}
	mi := &file_user_v1_merchant_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantByKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantByKeyResponse) ProtoMessage() {}

func (x *GetMerchantByKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_merchant_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantByKeyResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantByKeyResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_merchant_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetMerchantByKeyResponse) GetMerchant() *MerchantInfo {
	if x != nil {
		return x.Merchant
	}
	return nil
}

var File_user_v1_merchant_messages_proto protoreflect.FileDescriptor

const file_user_v1_merchant_messages_proto_rawDesc = "" +
	"\n" +
	"\x1fuser/v1/merchant_messages.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x02\n" +
	"\x15CreateMerchantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tsubdomain\x18\x02 \x01(\tR\tsubdomain\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x120\n" +
	"\x14platform_fee_percent\x18\x04 \x01(\x05R\x12platformFeePercent\x12&\n" +
	"\x0fowner_full_name\x18\x05 \x01(\tR\rownerFullName\x12\x1f\n" +
	"\vowner_phone\x18\x06 \x01(\tR\n" +
	"ownerPhone\x12%\n" +
	"\x0eowner_password\x18\a \x01(\tR\rownerPassword\"\x88\x02\n" +
	"\x16CreateMerchantResponse\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1c\n" +
	"\tsubdomain\x18\x02 \x01(\tR\tsubdomain\x12\x1f\n" +
	"\vschema_name\x18\x03 \x01(\tR\n" +
	"schemaName\x12\"\n" +
	"\rowner_user_id\x18\x04 \x01(\tR\vownerUserId\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.user.v1.MerchantStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"9\n" +
	"\x16GetMerchantByIDRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"L\n" +
	"\x17GetMerchantByIDResponse\x121\n" +
	"\bmerchant\x18\x01 \x01(\v2\x15.user.v1.MerchantInfoR\bmerchant\"\xb6\x02\n" +
	"\fMerchantInfo\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tsubdomain\x18\x03 \x01(\tR\tsubdomain\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1f\n" +
	"\vschema_name\x18\x05 \x01(\tR\n" +
	"schemaName\x120\n" +
	"\x14platform_fee_percent\x18\x06 \x01(\x05R\x12platformFeePercent\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x17.user.v1.MerchantStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"+\n" +
	"\x17GetMerchantByKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"M\n" +
	"\x18GetMerchantByKeyResponse\x121\n" +
	"\bmerchant\x18\x01 \x01(\v2\x15.user.v1.MerchantInfoR\bmerchant*\xa7\x01\n" +
	"\x0eMerchantStatus\x12\x1f\n" +
	"\x1bMERCHANT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MERCHANT_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18MERCHANT_STATUS_INACTIVE\x10\x02\x12\x1d\n" +
	"\x19MERCHANT_STATUS_SUSPENDED\x10\x03\x12\x1b\n" +
	"\x17MERCHANT_STATUS_PENDING\x10\x04B2Z0github.com/Sportinas/be-proto-gen/user/v1;userv1b\x06proto3"

var (
	file_user_v1_merchant_messages_proto_rawDescOnce sync.Once
	file_user_v1_merchant_messages_proto_rawDescData []byte
)

func file_user_v1_merchant_messages_proto_rawDescGZIP() []byte {
	file_user_v1_merchant_messages_proto_rawDescOnce.Do(func() {
		file_user_v1_merchant_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_merchant_messages_proto_rawDesc), len(file_user_v1_merchant_messages_proto_rawDesc)))
	})
	return file_user_v1_merchant_messages_proto_rawDescData
}

var file_user_v1_merchant_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_merchant_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_user_v1_merchant_messages_proto_goTypes = []any{
	(MerchantStatus)(0),              // 0: user.v1.MerchantStatus
	(*CreateMerchantRequest)(nil),    // 1: user.v1.CreateMerchantRequest
	(*CreateMerchantResponse)(nil),   // 2: user.v1.CreateMerchantResponse
	(*GetMerchantByIDRequest)(nil),   // 3: user.v1.GetMerchantByIDRequest
	(*GetMerchantByIDResponse)(nil),  // 4: user.v1.GetMerchantByIDResponse
	(*MerchantInfo)(nil),             // 5: user.v1.MerchantInfo
	(*GetMerchantByKeyRequest)(nil),  // 6: user.v1.GetMerchantByKeyRequest
	(*GetMerchantByKeyResponse)(nil), // 7: user.v1.GetMerchantByKeyResponse
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_user_v1_merchant_messages_proto_depIdxs = []int32{
	0, // 0: user.v1.CreateMerchantResponse.status:type_name -> user.v1.MerchantStatus
	8, // 1: user.v1.CreateMerchantResponse.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: user.v1.GetMerchantByIDResponse.merchant:type_name -> user.v1.MerchantInfo
	0, // 3: user.v1.MerchantInfo.status:type_name -> user.v1.MerchantStatus
	8, // 4: user.v1.MerchantInfo.created_at:type_name -> google.protobuf.Timestamp
	5, // 5: user.v1.GetMerchantByKeyResponse.merchant:type_name -> user.v1.MerchantInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_user_v1_merchant_messages_proto_init() }
func file_user_v1_merchant_messages_proto_init() {
	if File_user_v1_merchant_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_merchant_messages_proto_rawDesc), len(file_user_v1_merchant_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_merchant_messages_proto_goTypes,
		DependencyIndexes: file_user_v1_merchant_messages_proto_depIdxs,
		EnumInfos:         file_user_v1_merchant_messages_proto_enumTypes,
		MessageInfos:      file_user_v1_merchant_messages_proto_msgTypes,
	}.Build()
	File_user_v1_merchant_messages_proto = out.File
	file_user_v1_merchant_messages_proto_goTypes = nil
	file_user_v1_merchant_messages_proto_depIdxs = nil
}
