// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/user_service.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_v1_user_service_proto protoreflect.FileDescriptor

const file_user_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1/user_service.proto\x12\auser.v1\x1a\x1buser/v1/user_messages.proto\x1a\x1fuser/v1/merchant_messages.proto2\xb9\x01\n" +
	"\vUserService\x12Q\n" +
	"\x0eGetUserForAuth\x12\x1e.user.v1.GetUserForAuthRequest\x1a\x1f.user.v1.GetUserForAuthResponse\x12W\n" +
	"\x10GetMerchantByKey\x12 .user.v1.GetMerchantByKeyRequest\x1a!.user.v1.GetMerchantByKeyResponseB2Z0github.com/Sportinas/be-proto-gen/user/v1;userv1b\x06proto3"

var file_user_v1_user_service_proto_goTypes = []any{
	(*GetUserForAuthRequest)(nil),    // 0: user.v1.GetUserForAuthRequest
	(*GetMerchantByKeyRequest)(nil),  // 1: user.v1.GetMerchantByKeyRequest
	(*GetUserForAuthResponse)(nil),   // 2: user.v1.GetUserForAuthResponse
	(*GetMerchantByKeyResponse)(nil), // 3: user.v1.GetMerchantByKeyResponse
}
var file_user_v1_user_service_proto_depIdxs = []int32{
	0, // 0: user.v1.UserService.GetUserForAuth:input_type -> user.v1.GetUserForAuthRequest
	1, // 1: user.v1.UserService.GetMerchantByKey:input_type -> user.v1.GetMerchantByKeyRequest
	2, // 2: user.v1.UserService.GetUserForAuth:output_type -> user.v1.GetUserForAuthResponse
	3, // 3: user.v1.UserService.GetMerchantByKey:output_type -> user.v1.GetMerchantByKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_user_service_proto_init() }
func file_user_v1_user_service_proto_init() {
	if File_user_v1_user_service_proto != nil {
		return
	}
	file_user_v1_user_messages_proto_init()
	file_user_v1_merchant_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_service_proto_rawDesc), len(file_user_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_service_proto_goTypes,
		DependencyIndexes: file_user_v1_user_service_proto_depIdxs,
	}.Build()
	File_user_v1_user_service_proto = out.File
	file_user_v1_user_service_proto_goTypes = nil
	file_user_v1_user_service_proto_depIdxs = nil
}
