// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1/user_messages.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserForAuthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginSubdomain string                 `protobuf:"bytes,2,opt,name=login_subdomain,json=loginSubdomain,proto3" json:"login_subdomain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserForAuthRequest) Reset() {
	*x = GetUserForAuthRequest{}
	mi := &file_user_v1_user_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserForAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserForAuthRequest) ProtoMessage() {}

func (x *GetUserForAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserForAuthRequest.ProtoReflect.Descriptor instead.
func (*GetUserForAuthRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserForAuthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserForAuthRequest) GetLoginSubdomain() string {
	if x != nil {
		return x.LoginSubdomain
	}
	return ""
}

type GetUserForAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AccountStatus string                 `protobuf:"bytes,3,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	MerchantId    string                 `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SchemaName    string                 `protobuf:"bytes,6,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserForAuthResponse) Reset() {
	*x = GetUserForAuthResponse{}
	mi := &file_user_v1_user_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserForAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserForAuthResponse) ProtoMessage() {}

func (x *GetUserForAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserForAuthResponse.ProtoReflect.Descriptor instead.
func (*GetUserForAuthResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserForAuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserForAuthResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GetUserForAuthResponse) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *GetUserForAuthResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetUserForAuthResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetUserForAuthResponse) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

var File_user_v1_user_messages_proto protoreflect.FileDescriptor

const file_user_v1_user_messages_proto_rawDesc = "" +
	"\n" +
	"\x1buser/v1/user_messages.proto\x12\auser.v1\"Y\n" +
	"\x15GetUserForAuthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0flogin_subdomain\x18\x02 \x01(\tR\x0eloginSubdomain\"\xcd\x01\n" +
	"\x16GetUserForAuthResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12%\n" +
	"\x0eaccount_status\x18\x03 \x01(\tR\raccountStatus\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vschema_name\x18\x06 \x01(\tR\n" +
	"schemaNameB?Z=github.com/khoitran2003/sportinas-be-proto-gen/user/v1;userv1b\x06proto3"

var (
	file_user_v1_user_messages_proto_rawDescOnce sync.Once
	file_user_v1_user_messages_proto_rawDescData []byte
)

func file_user_v1_user_messages_proto_rawDescGZIP() []byte {
	file_user_v1_user_messages_proto_rawDescOnce.Do(func() {
		file_user_v1_user_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_messages_proto_rawDesc), len(file_user_v1_user_messages_proto_rawDesc)))
	})
	return file_user_v1_user_messages_proto_rawDescData
}

var file_user_v1_user_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_v1_user_messages_proto_goTypes = []any{
	(*GetUserForAuthRequest)(nil),  // 0: user.v1.GetUserForAuthRequest
	(*GetUserForAuthResponse)(nil), // 1: user.v1.GetUserForAuthResponse
}
var file_user_v1_user_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_user_messages_proto_init() }
func file_user_v1_user_messages_proto_init() {
	if File_user_v1_user_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_messages_proto_rawDesc), len(file_user_v1_user_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_user_messages_proto_goTypes,
		DependencyIndexes: file_user_v1_user_messages_proto_depIdxs,
		MessageInfos:      file_user_v1_user_messages_proto_msgTypes,
	}.Build()
	File_user_v1_user_messages_proto = out.File
	file_user_v1_user_messages_proto_goTypes = nil
	file_user_v1_user_messages_proto_depIdxs = nil
}
