// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment/v1/payment_service.proto

package paymentv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_payment_v1_payment_service_proto protoreflect.FileDescriptor

const file_payment_v1_payment_service_proto_rawDesc = "" +
	"\n" +
	" payment/v1/payment_service.proto\x12\n" +
	"payment.v1\x1a\x1cgoogle/api/annotations.proto\x1a!payment/v1/payment_messages.proto2\xb4\x03\n" +
	"\x0ePaymentService\x12x\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a!.payment.v1.CreatePaymentResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/public/payments\x12\x98\x01\n" +
	"\x12CheckPaymentStatus\x12%.payment.v1.CheckPaymentStatusRequest\x1a&.payment.v1.CheckPaymentStatusResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/public/payments/{booking_id}/status\x12\x8c\x01\n" +
	"\rCancelPayment\x12 .payment.v1.CancelPaymentRequest\x1a!.payment.v1.CancelPaymentResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/v1/public/payments/{booking_id}/cancelB8Z6github.com/Sportinas/be-proto-gen/payment/v1;paymentv1b\x06proto3"

var file_payment_v1_payment_service_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),       // 0: payment.v1.CreatePaymentRequest
	(*CheckPaymentStatusRequest)(nil),  // 1: payment.v1.CheckPaymentStatusRequest
	(*CancelPaymentRequest)(nil),       // 2: payment.v1.CancelPaymentRequest
	(*CreatePaymentResponse)(nil),      // 3: payment.v1.CreatePaymentResponse
	(*CheckPaymentStatusResponse)(nil), // 4: payment.v1.CheckPaymentStatusResponse
	(*CancelPaymentResponse)(nil),      // 5: payment.v1.CancelPaymentResponse
}
var file_payment_v1_payment_service_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	1, // 1: payment.v1.PaymentService.CheckPaymentStatus:input_type -> payment.v1.CheckPaymentStatusRequest
	2, // 2: payment.v1.PaymentService.CancelPayment:input_type -> payment.v1.CancelPaymentRequest
	3, // 3: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.CreatePaymentResponse
	4, // 4: payment.v1.PaymentService.CheckPaymentStatus:output_type -> payment.v1.CheckPaymentStatusResponse
	5, // 5: payment.v1.PaymentService.CancelPayment:output_type -> payment.v1.CancelPaymentResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_service_proto_init() }
func file_payment_v1_payment_service_proto_init() {
	if File_payment_v1_payment_service_proto != nil {
		return
	}
	file_payment_v1_payment_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_service_proto_rawDesc), len(file_payment_v1_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_service_proto_depIdxs,
	}.Build()
	File_payment_v1_payment_service_proto = out.File
	file_payment_v1_payment_service_proto_goTypes = nil
	file_payment_v1_payment_service_proto_depIdxs = nil
}
