// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: booking/v1/booking_service.proto

package bookingv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_booking_v1_booking_service_proto protoreflect.FileDescriptor

const file_booking_v1_booking_service_proto_rawDesc = "" +
	"\n" +
	" booking/v1/booking_service.proto\x12\n" +
	"booking.v1\x1a booking/v1/booking_message.proto\x1a\x1cgoogle/api/annotations.proto2\xfe\x05\n" +
	"\x0eBookingService\x12x\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a!.booking.v1.CreateBookingResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/public/bookings\x12f\n" +
	"\n" +
	"GetBooking\x12\x1d.booking.v1.GetBookingRequest\x1a\x13.booking.v1.Booking\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/public/bookings/{id}\x12r\n" +
	"\fListBookings\x12\x1f.booking.v1.ListBookingsRequest\x1a .booking.v1.ListBookingsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/public/bookings\x12\x8a\x01\n" +
	"\x13UpdateBookingStatus\x12&.booking.v1.UpdateBookingStatusRequest\x1a\x13.booking.v1.Booking\"6\x82\xd3\xe4\x93\x020:\x01*2+/api/v1/public/bookings/{booking_id}/status\x12\x97\x01\n" +
	"\x11CheckAvailability\x12$.booking.v1.CheckAvailabilityRequest\x1a%.booking.v1.CheckAvailabilityResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/v1/public/bookings/check-availability\x12o\n" +
	"\x16GetResourceOccupancies\x12).booking.v1.GetResourceOccupanciesRequest\x1a*.booking.v1.GetResourceOccupanciesResponseB8Z6github.com/Sportinas/be-proto-gen/booking/v1;bookingv1b\x06proto3"

var file_booking_v1_booking_service_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),           // 0: booking.v1.CreateBookingRequest
	(*GetBookingRequest)(nil),              // 1: booking.v1.GetBookingRequest
	(*ListBookingsRequest)(nil),            // 2: booking.v1.ListBookingsRequest
	(*UpdateBookingStatusRequest)(nil),     // 3: booking.v1.UpdateBookingStatusRequest
	(*CheckAvailabilityRequest)(nil),       // 4: booking.v1.CheckAvailabilityRequest
	(*GetResourceOccupanciesRequest)(nil),  // 5: booking.v1.GetResourceOccupanciesRequest
	(*CreateBookingResponse)(nil),          // 6: booking.v1.CreateBookingResponse
	(*Booking)(nil),                        // 7: booking.v1.Booking
	(*ListBookingsResponse)(nil),           // 8: booking.v1.ListBookingsResponse
	(*CheckAvailabilityResponse)(nil),      // 9: booking.v1.CheckAvailabilityResponse
	(*GetResourceOccupanciesResponse)(nil), // 10: booking.v1.GetResourceOccupanciesResponse
}
var file_booking_v1_booking_service_proto_depIdxs = []int32{
	0,  // 0: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	1,  // 1: booking.v1.BookingService.GetBooking:input_type -> booking.v1.GetBookingRequest
	2,  // 2: booking.v1.BookingService.ListBookings:input_type -> booking.v1.ListBookingsRequest
	3,  // 3: booking.v1.BookingService.UpdateBookingStatus:input_type -> booking.v1.UpdateBookingStatusRequest
	4,  // 4: booking.v1.BookingService.CheckAvailability:input_type -> booking.v1.CheckAvailabilityRequest
	5,  // 5: booking.v1.BookingService.GetResourceOccupancies:input_type -> booking.v1.GetResourceOccupanciesRequest
	6,  // 6: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.CreateBookingResponse
	7,  // 7: booking.v1.BookingService.GetBooking:output_type -> booking.v1.Booking
	8,  // 8: booking.v1.BookingService.ListBookings:output_type -> booking.v1.ListBookingsResponse
	7,  // 9: booking.v1.BookingService.UpdateBookingStatus:output_type -> booking.v1.Booking
	9,  // 10: booking.v1.BookingService.CheckAvailability:output_type -> booking.v1.CheckAvailabilityResponse
	10, // 11: booking.v1.BookingService.GetResourceOccupancies:output_type -> booking.v1.GetResourceOccupanciesResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_service_proto_init() }
func file_booking_v1_booking_service_proto_init() {
	if File_booking_v1_booking_service_proto != nil {
		return
	}
	file_booking_v1_booking_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_service_proto_rawDesc), len(file_booking_v1_booking_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_service_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_service_proto_depIdxs,
	}.Build()
	File_booking_v1_booking_service_proto = out.File
	file_booking_v1_booking_service_proto_goTypes = nil
	file_booking_v1_booking_service_proto_depIdxs = nil
}
